### ISSUE TITLE
Translatin - Merge sentences 14 and 83

### ISSUE THREAD

**Issue by Jibec** [osm-fr/osmose-frontend#1]
Can you please merge the sentences 14 and 83 ?
https://www.transifex.com/projects/p/osmose/translate/#ro/frontend/24588181?q=help
https://www.transifex.com/projects/p/osmose/translate/#fr/frontend/24588181?q=help

Both are talking about help on osm wiki/wiki, no need to have two sentences, is it ?

**Comment by frodrigo** [comment]
Not sure what about, but no more problem.
