### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by rugk** [osm-fr/osmose-frontend#106]
> When I manually input https://osmose.openstreetmap.fr , it automatically redirects me to osmose.openstreetmap.fr/en/map/ , without the https:// out front.

from original report in https://github.com/EFForg/https-everywhere/issues/16463 

Expected: properly support HTTPS. HTTPS should be the default nowadays! It's 2018.

---

forwarded from https://github.com/openstreetmap/operations/issues/241

**Comment by frodrigo** [comment]
Redirect come from:
https://github.com/osm-fr/osmose-frontend/blob/master/bottle_gettext.py#L88
It seem to use the original scheme to build the redirected URL.
Need to be debugged with an HTTP setup. cc @jocelynj 

Btw, since almost all browsers now supporter access to localhost in HTTP from HTTPS we can now use only HTTPS (cc @don-vip)

**Comment by jocelynj** [comment]
The issue might be because osmose server is behind a proxy, which means it is always accessed in http. To get the https/http information, we should look at X-Forwarded-Proto.

**Comment by rugk** [comment]
>  behind a proxy, which means it is always accessed in http. 

For security reasons, you should, obviously, also switch that URL there to HTTPS.

**Comment by don-vip** [comment]
Agreed: for the JOSM remote control link there is only one "browser" (Safari) where HTTP access from HTTPS website does not work and we care about it as much as they care about W3C standards. For all other browsers (Firefox, Chrome, IE, Edge, Opera), it works fine.

**Comment by Almtesh** [comment]
I noticed it too, but when you are on the site and put again the https, the site stays in HTTPS. Actually, it only turns back to HTTP when you go on the site for the first time and when you just loged in.

**Comment by jocelynj** [comment]
@frodrigo Can we add this code to our bottle configuration ?
https://bottlepy.org/docs/dev/faq.html?highlight=proxy#problems-with-reverse-proxies

```python
def fix_environ_middleware(app):
  def fixed_app(environ, start_response):
    environ['wsgi.url_scheme'] = 'https'
    environ['HTTP_X_FORWARDED_HOST'] = 'example.com'
    return app(environ, start_response)
  return fixed_app

app = bottle.default_app()
app.wsgi = fix_environ_middleware(app.wsgi)
```

**Comment by frodrigo** [comment]
`X-Forwarded-Proto` and `X-Forwarded-Host` should be set by reverse proxy into the request. It is the case today?

**Comment by jocelynj** [comment]
> `X-Forwarded-Proto` and `X-Forwarded-Host` should be set by reverse proxy into the request. It is the case today?

We are setting X-Real-IP/X-Forwarded-For/X-Forwarded-Proto here:

https://github.com/osm-fr/ansible-scripts/blob/master/roles/proxycache/templates/nginx-site.j2#L23

I don't think that X-Forwarded-Host is set - do we need it ?

**Comment by jocelynj** [comment]
Yes, this fis looks good. The only issue is that we should still look at url.scheme if not being a proxy.
