### ISSUE TITLE
problem to select

### ISSUE THREAD

**Issue by vinber** [osm-fr/osmose-frontend#117]
![peek 03-11-2018 09-25](https://user-images.githubusercontent.com/890869/47949877-895dcd00-df4a-11e8-905c-9bbbe0bcdc2b.gif)

Firefox 63 sur ubuntu

**Comment by frodrigo** [comment]
What did you do before to be in this state?

**Comment by vinber** [comment]
![peek 07-11-2018 09-49](https://user-images.githubusercontent.com/890869/48120503-947a6b00-e272-11e8-8944-f188dc822269.gif)

**Comment by arnaud-jacquemin** [comment]
Same problem here, using Firefox 65.0a1
