### ISSUE TITLE
Osmose tag editor removes trailing quote when its pair exists

### ISSUE THREAD

**Issue by iriman** [osm-fr/osmose-frontend#120]
An example is this [node](https://www.openstreetmap.org/node/5693708822#map=19/34.07784/49.67823) that I couldn't fix using osmose tag editor.

Today I edit it using osmose tag editor and pressed the valid button but didn't upload it, so seems it's hidden for now.

By looking at history found out I've also fixed it before but that time hadn't noticed that the ending quote isn't included.

**Comment by iriman** [comment]
it's up now: error 21127995889

**Comment by frodrigo** [comment]
The fix is here. Please, can you confirm it's ok for you?

**Comment by iriman** [comment]
I fixed that farmacy using omsose editor. seems ok. 
Thank you
