### ISSUE TITLE
A request for updating Persian localization

### ISSUE THREAD

**Issue by iriman** [osm-fr/osmose-frontend#122]
Hi, it seems Persian localization is not synced with transifex for a while. Does it have a schedule not reached yet?
for example compare the Persian translation of string "no bubbles at this zoom factor" at transifex with current translation on osmose website. There are some more strings like that, of course. thanks

**Comment by frodrigo** [comment]
The update is manual. We update the translation at the same time we update the source.
cc @jocelynj

**Comment by jocelynj** [comment]
Last time I checked, this git repository was already updated on https://github.com/osm-fr/osmose-frontend/blob/master/po/fa.po#L321

> msgid "no bubbles at this zoom factor"
> msgstr "در این بزرگ‌نمایی نشانه‌ای نمی‌بینید"

@iriman can you confirm if the string above is the correct one ?

**Comment by iriman** [comment]
Yes, this is the expected translation.

**Comment by iriman** [comment]
this one is the old version of this translation on transifex.

**Comment by iriman** [comment]
Yes, seems solved. I can't find any problem. thanks!
