### ISSUE TITLE
Move +, - and ~ symbols in popup layout in CSS :before rules to ease copy/pasting

### ISSUE THREAD

**Issue by mlorant** [osm-fr/osmose-frontend#126]
While integrating some elements using Osmose, I needed to copy data directly from the pop-up (e.g names and refs...). The OSM iD frontend allow pasting "key=value" format which is nice, since a simple copy from Osmose can be replicated easily.

However, each key/value properties are prepended by a symbol to indicate if it's an addition, removal or change. That's nice, but it makes the copying harder, since selecting the whole line also select this character, and thus, when pasting to iD, the character remains.

I've just download one page of Osmose to try quickly, I think it just needs to [remove those symbols in popup.tpl](https://github.com/osm-fr/osmose-frontend/blob/23a953455ded9ab3d48bcbc708d5352b2d5a1a6b/views/map/popup.tpl#L37) and add new CSS rules in [Osmose.Editor.css](https://github.com/osm-fr/osmose-frontend/blob/23a953455ded9ab3d48bcbc708d5352b2d5a1a6b/static/map/Osmose.Editor.css#L18) file:

```
.bulle_elem .add:before {
     content: " + ";
}
.bulle_elem .del:before {
     content: " - ";
}
.bulle_elem .mod:before {
     content: " ~ ";
}
```
Doing so, I can simply triple-clicking on the line to copy, and the prefix is ignored. 

I guess the PR takes 5~10 minutes to be prepared but forking and installing Osmose locally for the first time seems to take 10x that time... So I let everyone with a configured setup do it :-)

**Comment by frodrigo** [comment]
Done.
