### ISSUE TITLE
No rechecks for false positive?

### ISSUE THREAD

**Issue by dex2000** [osm-fr/osmose-frontend#128]
it looks like that the false-positive-database is not connected with the error-db or not checked for changes.

For example:
http://osmose.openstreetmap.fr/de/errors/false-positive?source=9331&item=3150&class=1
the second "false positive" was fixed a year ago: http://www.openstreetmap.org/way/358890292/history 

I think that repaired errors should automatically removed from the false-positve-list. Because its not an error.

**Comment by frodrigo** [comment]
Fixed with uuid.
