### ISSUE TITLE
API - by osm object

### ISSUE THREAD

**Issue by nlehuby** [osm-fr/osmose-frontend#130]
Could we have an endpoint in the API to get the errors about an OSM object by id ?

something like `http://osmose.openstreetmap.fr/fr/api/0.2/elem/way428442917`

**Comment by nlehuby** [comment]
I'd rather have a mure usual json format like:
```
{
  "errors": [
    {
      "error_id": "22875703229",
      "item": "7070",
      "lat": "44.9947355",
      "lon": "1.2514080"
    }
  ]
}
```

but yes, this fits my needs, thanks!

**Comment by frodrigo** [comment]
As this API point is no more under heavy load, I can make it more json-like:
http://beta.osmose.openstreetmap.fr/fr/api/0.3beta/issues?osm_type=node&osm_id=3216121187&full=true

**Comment by nlehuby** [comment]
:+1:

**Comment by frodrigo** [comment]
It's now deployed on main server.
