### ISSUE TITLE
Simplification des résultats tabulés après redécoupage des pays

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-frontend#131]
Hello,

Puisqu'il y a eu redécoupage des pays pour l'analyse (ex. par département en France), est-ce qu'il est intéressant de simplifier la visu. tabulée en virant de la liste déroulante (et donc des résultats) toutes les zones qui ne sont plus analysées comme telles ?
(ex. ici https://osmose.openstreetmap.fr/fr/errors/?country=&item=2060&level=1%2C2%2C3 )

**Comment by frodrigo** [comment]
Non.
Mais c'est quand même à améliorer.
