### ISSUE TITLE
rawedit does not work

### ISSUE THREAD

**Issue by HubMiner** [osm-fr/osmose-frontend#134]
Clicking "rawedit" creates a new window:

URL: http://rawedit.openstreetmap.fr/edit/node/6202756387
Message: 
Forbidden
You don't have permission to access /edit/node/6202756387 on this server.

**Comment by HubMiner** [comment]
I found what I need when I clicked "Edit" (Tags Editor).  Perhaps rawedit should be removed or commented what it is for.

**Comment by frodrigo** [comment]
Removed.
