### ISSUE TITLE
Random interface language

### ISSUE THREAD

**Issue by HubMiner** [osm-fr/osmose-frontend#141]
Today (May 7), english interface for Tag Editor switched to French language.

**Comment by jocelynj** [comment]
I'm not seeing this issue, so we will need more information.

Which URL are you using?
Can you provide a screenshot?

**Comment by frodrigo** [comment]
It's a know issue, the translation system is not thread safe. On server load it can randomly serve an other language.

**Comment by frodrigo** [comment]
API reworked.
