### ISSUE TITLE
Remove country azores and canada_ontario

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-frontend#150]

**Comment by frodrigo** [comment]
Remove country azores and canadata_ontario

**Comment by jocelynj** [comment]
C'est supprimé.

Pour les stats, est-ce que tu veux déplacer les stats azores vers portugal_azores. Si oui, est-ce qu'il suffit de changer le source_id de la nouvelle table stats ?

**Comment by frodrigo** [comment]
Oui
