### ISSUE TITLE
More data in the by user RSS feed

### ISSUE THREAD

**Issue by Phyks** [osm-fr/osmose-frontend#155]
Hi,

I've recently discovered the _by user_ RSS feed and this is really a great tool, providing very fast feedback on errors in latest changesets, making it easy to keep up to date with Osmose errors!

However, the RSS entries are somehow minimalistic and in my opnion, they could use a bit more details. What about providing the same infos as in the error infobox in the RSS entries?

At the moment, I often have to click the item (actually, the "E" link as the main link on the title does not auto-open the tooltip for the right marker) to have the details (summary of the error, etc).

Additionally, having the "mark fixed" and "discard as false positive" links right in the RSS entry would be super useful as well to handle Osmose issues quicker.

Thanks!
Best,

**Comment by frodrigo** [comment]
TODO

- [ ] Add more info to RSS
- [ ] Add link to done/false positive

- [ ] Optionally, open the issue popup on the map


@Phyks @francois2metz @LePetitTim interested in fixing this?
It's an easy issue to fix.

**Comment by Phyks** [comment]
I had a very quick look.

> Optionally, open the issue popup on the map

This should actually probably be done in a broader context than just RSS. Ideally, clicking the `pos` column on https://osmose.openstreetmap.fr/fr/byuser/Phyks should open the popup I think. Currently, it just sends back to the map view but does not interfer with the previously used map settings, so that sometimes the marker of the issue is not even visible (due to priority filtering for instance).

> Add more info to RSS

There seems to be two different entry points for RSS export (contrary to the HTML views which includes one another):
1. https://github.com/osm-fr/osmose-frontend/blob/master/views/errors/list.rss which is used for any RSS export but `byuser`.
2. https://github.com/osm-fr/osmose-frontend/blob/master/views/byuser/byuser.rss.tpl which is used for `byuser` 

The second one is much more complete and readable than the first one I think, they should probably be merged together?

**Comment by frodrigo** [comment]
> Optionally, open the issue popup on the map

Yes, this is a more generic and independent issue.

> Add more info to RSS

Yes can be merged.

**Comment by vinber** [comment]
When I receive rss (thunderbird or liferea), I see these 

![Capture d’écran de 2019-12-12 15-50-30](https://user-images.githubusercontent.com/890869/70727763-7ea26980-1d00-11ea-8fcd-9de935e3c294.png)

- Site web : url open a map, but i don't know which issue is concerned -> open the issue pop-up on the map :D 
- In the text, url are very useful but not linked, I need to copy/paste url in firefox to open osm or josm (http://localhost....) -> linked url would be very cool

**Comment by frodrigo** [comment]
New links now open the popup, thank to @gileri .
