### ISSUE TITLE
Mapillary link no longer highlighted on link

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-frontend#156]
* I select "street objects".
* I select a green “pin”
* I click the tag    +mapillary = TubH-8aQGqFf8w8LJ43imQ  (the link corresponds to a real example http://www.mapillary.com/map/im/TubH-8aQGqFf8w8LJ43imQ )
* opens the photo of mapillary
* the object is no longer highlighted as it used to be. No object is highlighted!

**Comment by frodrigo** [comment]
The link to Mapillary need to be fixed with https://www.mapillary.com/app/?focus=photo&pKey=TubH-8aQGqFf8w8LJ43imQ&lat=45.33104839999993&lng=7.720083499999987&z=17&points=true

@Phyks @francois2metz @LePetitTim interested in fixing this? It's an easy issue to fix.

**Comment by canfe** [comment]
> interested in fixing this? It's an easy issue to fix.

Sure!
Of course I'm interested!
How do I do it?

**Comment by frodrigo** [comment]
We lost a config in the last two commits https://github.com/osm-fr/osmose-frontend/commits/master/tools/tag2link_sources.xml

(If you want to test it's with the docker setup https://github.com/osm-fr/osmose-frontend/tree/master/docker )

**Comment by frodrigo** [comment]
Done.
