### ISSUE TITLE
Filter by class of an issue

### ISSUE THREAD

**Issue by zzptichka** [osm-fr/osmose-frontend#158]
Sometimes I'd like to be able to filter only certain class of an issue. For example, show on the map only class 34 of item 8300. So I can quickly fix them and avoid going through hundreds of other 8300 issues, like animal crossings that I don't want to touch.
Is there a hidden parameter to filter by class right now?
If not, will it be possible to add it?
Thanks.

**Comment by zzptichka** [comment]
OK, turns out it's pretty straighforward - just add `class=xxxx` parameter in the URL.

**Comment by frodrigo** [comment]
Yes the hidden parameter to filter on class is... `class`.

The filter is not present from the main map page. But you can add it in the url or click from list pages : http://osmose.openstreetmap.fr/en/errors/?item=8300&class=4
