### ISSUE TITLE
"Relation analyser" link is dead

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/osmose-frontend#165]
Hello
The "Relation analyser" link point to http://analyser.openstreetmap.fr/cgi-bin/index.py that doesn't work. Maybe change or remove this link ?

**Comment by aroche** [comment]
The other link ("analyse2") : http://polygons.openstreetmap.fr/~osmbin/analyse-relation-open.py is dead as well (error 403)

**Comment by frodrigo** [comment]
https://github.com/osm-fr/infrastructure/issues/147

**Comment by frodrigo** [comment]
First links removed.
Second now pointing to http://polygons.openstreetmap.fr/
Open to better suggestion.
