### ISSUE TITLE
"Service Unavailable" for 6+ hours

### ISSUE THREAD

**Issue by EwenH** [osm-fr/osmose-frontend#167]
On a number of occasions, I have received the following error for extended periods. Is this planned as the site has normally been available most of the time previously?

From Windows: Chrome and validated via IE Edge

_Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.25 (Debian) Server at osmose.openstreetmap.fr Port 80_

**Comment by frodrigo** [comment]
I just restart Apache, now it is working.

Osmose project is only ran by few volunteers. We have not always the availability to fix or improve the service.

Help is greatly welcome.

**Comment by frodrigo** [comment]
cc @jocelynj
