### ISSUE TITLE
Wrong link for ref:INSEE code on item 6040

### ISSUE THREAD

**Issue by Stefal** [osm-fr/osmose-frontend#170]
Hi!
On item 6040 (Municipality name) the ref:INSEE tag provide a link to the mérimée (monument historique) database
example : http://osmose.openstreetmap.fr/fr/error/34433432452

![image](https://user-images.githubusercontent.com/8255984/67547861-7fefe680-f700-11e9-936c-f066dfac11cb.png)

**Comment by frodrigo** [comment]
It use tag2links. Please, report to this project.
