### ISSUE TITLE
api 0.3beta : database error at issues with full parameter

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-frontend#191]
hello,
it's ok with api 0.2 :
http://osmose.openstreetmap.fr/fr/api/0.2/errors?country=sweden&item=1230
http://osmose.openstreetmap.fr/fr/api/0.2/errors?country=sweden&item=1230&full=True

it's ok with api 0.3 :
http://osmose.openstreetmap.fr/fr/api/0.3beta/issues?country=sweden&item=1230

but since last update "Internal Server Error" for :
http://osmose.openstreetmap.fr/fr/api/0.3beta/issues?country=sweden&item=1230&full=True

**Comment by frodrigo** [comment]
Fixed. Thank you for report.
