### ISSUE TITLE
Issues with item=1080 (Orphan Nodes) don't provide the node elements

### ISSUE THREAD

**Issue by SilentSpike** [osm-fr/osmose-frontend#194]
Issues with `item=1080` don't provide the nodes (`elems`) in question as would be expected. For example:

https://osmose.openstreetmap.fr/en/api/0.3beta/issue/ed23244c-9053-1014-c4dc-4d5f06c8394e

I suppose this is perhaps more relevant to the back end, but figure I should report it here since I'm seeing the behaviour on the front end.

**Comment by frodrigo** [comment]
elems is not a required properties.

In this case the list could be very large. It is done by clustering. Fetching the objects should require extra computing. I do not plan to change it.

**Comment by SilentSpike** [comment]
👍 Reasonable, can close this as intended behaviour
