### ISSUE TITLE
open relation in josm doesnt works as espected

### ISSUE THREAD

**Issue by dex2000** [osm-fr/osmose-frontend#196]
Links for open in JOSM nodes/ways or for relations are different:
`osmose.openstreetmap.fr/de/josm_proxy?import?url=https://www.openstreetmap.org//api/0.6/relation/RELATIONID/full`
vs:
`osmose.openstreetmap.fr/de/josm_proxy?load_object?objects=nNODEID`

node and ways works, but relation every time asks for REAUTH.

Why are the Links different? 
`osmose.openstreetmap.fr/de/josm_proxy?load_object?objects=rRELATIONID `
will work as expected.

**Comment by frodrigo** [comment]
`osmose.openstreetmap.fr/de/josm_proxy?import?url=https://www.openstreetmap.org//api/0.6/relation/RELATIONID/full` load the content of the relation, but `osmose.openstreetmap.fr/de/josm_proxy?load_object?objects=rRELATIONID ` not.

What is `REAUTH`? I do not see this issue.

**Comment by dex2000** [comment]
For example:
http://osmose.openstreetmap.fr/de/josm_proxy?import?url=https://www.openstreetmap.org//api/0.6/relation/163389/full

i got a message: login on the server openstreetmap.org has failed, login again.

http://osmose.openstreetmap.fr/de/josm_proxy?load_object?objects=r163389 instead works normally

**Comment by frodrigo** [comment]
But this on works eg:
http://osmose.openstreetmap.fr/de/josm_proxy?import?url=https://www.openstreetmap.org/api/0.6/relation/6455484/full

cc @don-vip

**Comment by dex2000** [comment]
frodrigo: is it a josm-problem? I cannot see any difference between my link and your link (expect the IDs)

**Comment by frodrigo** [comment]
@dex2000 Still an issue for you?

**Comment by dex2000** [comment]
i have saved the password now and it asks never.
