### ISSUE TITLE
items endpoint returns no results if item=0

### ISSUE THREAD

**Issue by SilentSpike** [osm-fr/osmose-frontend#204]
See: http://osmose.openstreetmap.fr/en/api/0.3beta/items/0/class/1?langs=en

Would expect this to return the strings for the overlapping building error:
https://osmose.openstreetmap.fr/en/errors/?item=0&class=1

**Comment by SilentSpike** [comment]
Looks like this may already be fixed in https://github.com/frodrigo/osmose-frontend/commit/01738874d19d61dd79a057f4532cbabff8c47827

**Comment by frodrigo** [comment]
Yes. Sorry already fixed, but forgot to deploy the fix. Done now.
