### ISSUE TITLE
Request: langs parameter for issue endpoint (dynamic strings)

### ISSUE THREAD

**Issue by SilentSpike** [osm-fr/osmose-frontend#205]
Example:

https://osmose.openstreetmap.fr/en/api/0.3beta/issue/4cc3631b-d931-337e-aba3-794109397155?langs=de
would return the results of
https://osmose.openstreetmap.fr/de/api/0.3beta/issue/4cc3631b-d931-337e-aba3-794109397155

Currently in the iD layer I'm just extracting relevant details from the subtitle where necessary and displaying only those to the user.

This works fine enough, however it would be nice to be able to specify a language without changing the endpoint URL and show these strings directly (and to link the localised help URL).

**Comment by frodrigo** [comment]
Yes the `langs` parameter have to be added here also.

**Comment by frodrigo** [comment]
It available now.

Note: soon the api will be at the root, without language in the path. The 0.3 API is now fully implemented and will be released soon.
