### ISSUE TITLE
Chinese characters cannot be displayed

### ISSUE THREAD

**Issue by qa003qa003** [osm-fr/osmose-frontend#206]
Chinese characters cannot be displayed
![screenshot-osmose openstreetmap fr-2020 02 08-09_00_30](https://user-images.githubusercontent.com/14744672/74076218-96bd0d80-4a51-11ea-97cb-4e26bd6f4e6a.png)

**Comment by frodrigo** [comment]
Moved to OSM-FR, source of the layer https://github.com/osm-fr/infrastructure/issues/146
