### ISSUE TITLE
Where is "potential misspelling"?

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-frontend#214]
Hello, I am a Polish translator. On Transifex frontend there is a string to translate "potential misspelling". I translate only in context, so I need to see where it is used before translating, but I can't find it anywhere on the Osmose website.

**Comment by frodrigo** [comment]
It is on the left menu. Ensure you display all with filters.

**Comment by maro-21** [comment]
Ok, I found it in the English version. It's the issue 5050. In the Polish version in this place there is "test soundex" - where does this come from? No such string in pl.po file. I thought it should be an English one "potential misspeling" if it's untranslated.
https://github.com/osm-fr/osmose-frontend/blob/85cae04a776cb971aacd14279bd0906cb241daed/po/pl.po#L1557-L1558

**Comment by frodrigo** [comment]
cc @jocelynj

**Comment by maro-21** [comment]
I translated the string already, let's see if it is correct after the next translations update

**Comment by jocelynj** [comment]
That's very strange.

I confirm that the string "test soundex" is in the database for item 5050 for pl translation. It is also present for other languages. I think that we changed the english original text, without purging already present translations. The frontend's update script for menu translation is not removing previous translations.

@frodrigo: do you confirm that we changed the english string for item 5050?

**Comment by jocelynj** [comment]
I've regenerated all translations for the menu on frontend database.

**Comment by maro-21** [comment]
Thanks! It works now, "potential misspeling" appeared on the website.

**Comment by maro-21** [comment]
similar question: where can I find "Load the fix in" and "Add the new object in"?
It's here in the code
https://github.com/osm-fr/osmose-frontend/blob/48ec170be443b7c0525b81c1176f84fcd19d5169/views/map/popup.tpl#L36
but I can't find it on Osmose website.
