### ISSUE TITLE
Source link: Internal Server Error

### ISSUE THREAD

**Issue by kudlav** [osm-fr/osmose-frontend#216]
1. Visit this problem details: http://osmose.openstreetmap.fr/cs/error/9bd633b7-5e12-cd80-6d49-e46e6ad60f8e
2. Click on the _source_ link: http://osmose.openstreetmap.fr/errors/?item=xxxx&source=https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_DuplicateValue.py#L42
3. _Internal server error_ appeared

**Comment by frodrigo** [comment]
Yes knew issue. The source field is not filled with source id but source code url.
