### ISSUE TITLE
exclude (or simply include) type of warnings on byuser-page?

### ISSUE THREAD

**Issue by dex2000** [osm-fr/osmose-frontend#22]
Is it possible to exclude warnings by type on the byuser-page? (http://osmose.openstreetmap.fr/de/byuser/)
Or similar include or select the types of warnings?

If not, is this a feature request... ;)

In addition for that (maybe new issue?) Is  it possible to get more than 500 "byuser-bugs", or "next" 500 "byuser-bugs"

**Comment by frodrigo** [comment]
Yes.
http://osmose.openstreetmap.fr/de/byuser/?username=frodrigo&item=1060,2060
On this page 500 is the upper limit, but you can filter.

**Comment by dex2000** [comment]
ah helps a little bit, thx, but exclude should be better
