### ISSUE TITLE
Error description [object Object] [object Object] in popup

### ISSUE THREAD

**Issue by kudlav** [osm-fr/osmose-frontend#223]
Sometimes I am unable to see error description of any issue. I have to reload page and after that it's ok. No error in javascript console. It's for the second time I see this issue.

Firefox 74.0 (64 bit)

Issue in the screenshot:
http://osmose.openstreetmap.fr/cs/error/6741793d-fdde-020d-5ab4-3a7e672fd03b

![obrazek](https://user-images.githubusercontent.com/11516259/76704449-6401d700-66d9-11ea-8499-bb2da38c7bab.png)

**Comment by frodrigo** [comment]
This issue is already fixed. Maybe you have some popup content in your local cache.
