### ISSUE TITLE
Name of the Lithuanian language in the menu

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-frontend#224]
Lithuanian is the only language in the menu which name is in English.
It should be changed to `Lietuvių`.
https://github.com/osm-fr/osmose-frontend/blob/c92abe4ca773f05b7307b8deb28fec171a3f2ab7/tools/utils.py#L30

**Comment by jocelynj** [comment]
Thanks for reporting this issue.

I will do this change tonight.
