### ISSUE TITLE
Error not removed from frontend when class is now empty

### ISSUE THREAD

**Issue by jocelynj** [osm-fr/osmose-frontend#225]
The incorrect error is http://osmose.openstreetmap.fr/fr/error/ba1e3dcb-6631-70b3-b2d1-30ca256913e2, and is about node 6852748842.

Looking at result file `/data/work/osmose/results/Analyser_Sax-france_pays_de_la_loire_loire_atlantique.bz2` on osm153, it contains the following:
```
<class id="9014002" item="9014" level="2" tag="tag,public_transport">
...
<error class="9014007" subclass="1428913922">
<location lat="47.2535683" lon="-1.7718252" />
<node id="6852748842" lat="47.2535683" lon="-1.7718252" version="5" user="StephaneP">
...
<error class="9014008" subclass="210603856">
<location lat="47.2535683" lon="-1.7718252" />
<node id="6852748842" lat="47.2535683" lon="-1.7718252" version="5" user="StephaneP">
```

But no error with this class. I think that https://github.com/osm-fr/osmose-frontend/blob/master/tools/update.py#L257 is missing some code to remove old errors when the class is now empty.

**Comment by frodrigo** [comment]
Marker removed.
