### ISSUE TITLE
docker-compose build fails

### ISSUE THREAD

**Issue by DavidMoraisFerreira** [osm-fr/osmose-frontend#227]
Hi,
When executing the [commands](https://github.com/DavidMoraisFerreira/osmose-backend/tree/master/docker):
`git clone https://github.com/osm-fr/osmose-frontend.git`
`cd osmose-frontend/docker`
`curl http://osmose.openstreetmap.fr/export/osmose-menu.sql.bz2 | bzcat > osmose-menu.sql`
`docker-compose build`
, I get the following error:

> (osmose-frontend-venv) david@orion ~/repos/osmose-frontend/docker (master*) $ sudo docker-compose build
> postgres uses an image, skipping
> Building frontend
> Step 1/20 : FROM python:2.7
>  ---> fbc983cb5352
> Step 2/20 : MAINTAINER Frédéric Rodrigo <fred.rodrigo@gmail.com>
>  ---> Using cache
>  ---> 4dc4808b1595
> Step 3/20 : RUN mkdir -p /data/work/root/results/
>  ---> Using cache
>  ---> deaee7870527
> Step 4/20 : RUN curl -sL http://deb.nodesource.com/setup_12.x -o nodesource_setup.sh &&     bash ./nodesource_setup.sh &&     apt update &&     apt install -y --no-install-recommends         bzip2         gettext         git         make         nodejs         postgresql-client         sudo &&     apt-get clean
>  ---> Using cache
>  ---> 9485f9c9e4fc
> Step 5/20 : ADD ./requirements.txt /data/project/osmose/frontend/requirements.txt
>  ---> Using cache
>  ---> 5d4737191f1a
> Step 6/20 : WORKDIR /data/project/osmose/frontend
>  ---> Using cache
>  ---> 3233b0b46d21
> Step 7/20 : RUN pip install -r requirements.txt
>  ---> Using cache
>  ---> 4bdda3891503
> Step 8/20 : RUN mkdir /data/project/osmose/frontend/web
>  ---> Using cache
>  ---> edaf9499f625
> Step 9/20 : ADD ./web/package.json /data/project/osmose/frontend/web/
>  ---> Using cache
>  ---> 60be44d865bb
> Step 10/20 : ADD ./web/package-lock.json /data/project/osmose/frontend/web/
>  ---> Using cache
>  ---> 397f4ffe08bc
> Step 11/20 : ADD ./web/webpack.config.js /data/project/osmose/frontend/web/
>  ---> Using cache
>  ---> 8830ff2a5841
> Step 12/20 : RUN mkdir ../node_modules &&     ln -s ../../node_modules web/node_modules &&     cd web &&     npm install
>  ---> Using cache
>  ---> 94fe18273037
> Step 13/20 : ADD ./web/static /data/project/osmose/frontend/web/static
>  ---> Using cache
>  ---> 01c8273c8f2a
> Step 14/20 : RUN cd web && npm run build
>  ---> Running in 4ef74698c8ed
> 
> osmose-frontend@0.0.0 build /data/project/osmose/frontend/web
> webpack
> 
> (node:18) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
> Hash: 3640716d98f6faf383ae
> Version: webpack 4.41.5
> Time: 16858ms
> Built at: 03/20/2020 9:24:48 PM
>  6 assets
> Entrypoint static = static/webpack.bundle-3640716d98f6faf383ae.js static/webpack.bundle-3640716d98f6faf383ae.js.map
> Entrypoint static/map = static/map/webpack.bundle-3640716d98f6faf383ae.js static/map/webpack.bundle-3640716d98f6faf383ae.js.map
>  [6] ./static/map/layers.js + 1 modules 5.61 KiB {1} [built]
>      | ./static/map/layers.js 3.53 KiB [built]
>      | ./static/map/Mapillary.js 2.08 KiB [built]
> [16] ./static/css/style.css 1.19 KiB {0} {1} [built]
> [17] /data/project/osmose/node_modules/css-loader!/data/project/osmose/node_modules/sprite-loader??ref--5-2!./static/css/style.css 732 bytes {0} {1} [built]
> [21] ./static/map/Osmose.Menu.js 8.12 KiB {1} [built]
> [22] ./static/map/Osmose.Doc.js 3.96 KiB {1} [built]
> [29] ./static/map/map.js 4.27 KiB {1} [built]
> [30] ./static/map/Osmose.Export.js 845 bytes {1} [built]
> [31] ./static/map/Osmose.Editor.js 10.2 KiB {1} [built]
> [32] ./static/map/Osmose.Marker.js 8.29 KiB {1} [built]
> [34] ./static/webpack.index.js 156 bytes {0} [built]
> [35] ./static/js/err_delete.js 929 bytes {0} [built]
> [36] ./static/js/sorttable.js 16.9 KiB {0} [built]
> [37] ./static/map/webpack.index.js 415 bytes {1} [built]
> [78] ./static/map/style.css 1.19 KiB {1} [built]
> [80] ./static/images/markers/markers-l.css 1.22 KiB {1} [built]
>     + 68 hidden modules
> 
> ERROR in ./static/images/markers/markers-l.css (/data/project/osmose/node_modules/css-loader!/data/project/osmose/node_modules/sprite-loader??ref--5-2!./static/images/markers/markers-l.css)
> Module build failed (from /data/project/osmose/node_modules/sprite-loader/index.js):
> Error: ENOENT: no such file or directory, stat '/data/project/osmose/frontend/web/static/images/markers/marker-l-1290.png'
>  @ ./static/images/markers/markers-l.css 4:14-151
>  @ ./static/map/webpack.index.js
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! osmose-frontend@0.0.0 build: `webpack`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the osmose-frontend@0.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2020-03-20T21_24_48_519Z-debug.log
> ERROR: Service 'frontend' failed to build: The command '/bin/sh -c cd web && npm run build' returned a non-zero code: 2
>

**Comment by frodrigo** [comment]
The file `web/static/images/markers/marker-l-1290.png` is missing in the repository. It a know issue.
Just copy an other random file from the directory as this name.

cc @jocelynj

**Comment by frodrigo** [comment]
Is now fixed.
