### ISSUE TITLE
ref:UAI leading to outdated URL

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-frontend#229]
In tag2link_sources.xml, the URL
https://github.com/osm-fr/osmose-frontend/blob/02dbee592089127c08a59afa6cab8302d5857d59/tools/tag2link_sources.xml#L168-L173
should be updated to:

https://www.education.gouv.fr/annuaire?field_type_etablissement=All&field_status=All&geo_point=keywords=%v%+

**Comment by frodrigo** [comment]
`tag2link_sources.xml` is a copy of the one from JOSM. First JSOM need to be fixed. If  it's OK. We need to update it.

Please check.

**Comment by Bibi56** [comment]
Corresponding ticket created: [JOSM 18967](https://josm.openstreetmap.de/ticket/18967).

**Comment by simon04** [comment]
@JOSM does no longer use `tag2link_sources.xml`. Instead, the formatter URLs are obtained from Wikidata. Here's the documentation: https://josm.openstreetmap.de/wiki/Help/Action/Tag2Link Here's the relevant JOSM ticket: https://josm.openstreetmap.de/ticket/13901

**Comment by frodrigo** [comment]
@simon04 JOSM directly query wikidata, or the result is cached/converted somewhere ?

**Comment by simon04** [comment]
The query is performed once at startup. Just now, I've extracted the relevant parts to a small separate repository: https://github.com/osmlab/tag2link

You might want to use https://github.com/osmlab/tag2link/blob/master/index.json directly.

**Comment by frodrigo** [comment]
@simon04 ok, thank you. I will look at this later. I have created a new issue for that https://github.com/osm-fr/osmose-frontend/issues/230

@Bibi56 for now I will do the change you required in the local copy of the XML.

**Comment by frodrigo** [comment]
@Bibi56 You URL does not work

**Comment by Bibi56** [comment]
@frodrigo, didin't you forget to substitute %v% by the tag value? I forgot an ampersand on my side

Well, you seem to be right, the url works but returns 0 result.
This search function "works" with fuzzy name matching.

I found another endpoint: https://www.education.gouv.fr/acce_public/search.php?mode=advanced
but it uses POST not GET, I don't know if it's an issue for you.

**Comment by frodrigo** [comment]
No, we cannot use post
