### ISSUE TITLE
Errors are assigned to the wrong user

### ISSUE THREAD

**Issue by bunnu** [osm-fr/osmose-frontend#23]
The list of errors created by an certain user, shows errors on elements which weren't created or last modified by this user.

Example: http://osmose.openstreetmap.fr/de/byuser/BRana

**Comment by frodrigo** [comment]
Osmose issues are assigned to last objects' editors part of the issue.
Don't take number of issue affected to you as quality level of yours contributions. More you contribute, more you have issues assigned to you. Even if you contribute with in best ways of the art.
