### ISSUE TITLE
Export to JOSM does nothing (404)

### ISSUE THREAD

**Issue by kartonage** [osm-fr/osmose-frontend#231]
Hej,

don't know exactly when but since a bit exporting to JOSM at any zoom level does nothing.
 404 (Not Found) is displayed by the browser consoles (tried with Firefox and Vivaldi, both latest).

In this particular case I tried exporting two issues of overlapping buildings.
The export link was

`https://osmose.openstreetmap.fr/en/josm_proxy?errors.josm?zoom=15&item=0000%2C0001&level=1%2C2%2C3&tags=&fixable=&limit=500&bbox=13.712053298950197%2C51.47165347013125%2C13.773765563964846%2C51.49677467073`

When I removed the `josm_proxy?`, the link was working as expected (loading objects in JOSM).

(note that the above link won't produce any objects to load anymore since I fixed the issues)

Best regards.

**Comment by frodrigo** [comment]
Fixed.

Few days ago we deploy internal refactoring and break some urls.
