### ISSUE TITLE
Broken links to user RSS feed

### ISSUE THREAD

**Issue by AndrewKvalheim** [osm-fr/osmose-frontend#233]
At [`/en/byuser/AndrewKvalheim`](https://osmose.openstreetmap.fr/en/byuser/AndrewKvalheim) is a link to [`/byuser/AndrewKvalheim.rss`](http://osmose.openstreetmap.fr/byuser/AndrewKvalheim.rss), which returns a 404. Prepending [`/en/`](http://osmose.openstreetmap.fr/en/byuser/AndrewKvalheim.rss) returns the expected RSS feed, but its self `<link>` tag still contains the broken link.

**Comment by frodrigo** [comment]
We broke this last week. Now fixed.
