### ISSUE TITLE
Frontend beta: Fails get /api/ 

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-frontend#234]
Hello,

Trying to edit an error causes this fail.

![Screenshot_2020-03-29 Osmose - Carte](https://user-images.githubusercontent.com/36087963/77843900-ceb71600-71a1-11ea-9550-d9cd9ffcab4c.png)

Do you need other info?

**Comment by frodrigo** [comment]
Ok. The editor is not working. I forgot to test it !
