### ISSUE TITLE
byuser/usérnáme_  ==>  Invalid path string. Expected UTF-8

### ISSUE THREAD

**Issue by ivanrome** [osm-fr/osmose-frontend#235]
Hello,

When I try to acces the feature, byuser when I'm logged in I get an error.

> Error: 400 Bad Request
> Sorry, the requested URL 'http://osmose.openstreetmap.fr/es/byuser/Iv%C3%A1n_?level=1' caused an error:
> 
> Invalid path string. Expected UTF-8

My username has an special character "á" and and a underscore at the end  : `Iván_`

According to the error, It looks like a problem with the encoding. Indeed, as you are using bottle framework, it looks like there is a problem while sending the request with bottle:

https://github.com/osm-fr/osmose-frontend/blob/314f4f0ed77f1deeacbd93f9913e48d7c9fd4b94/web/byuser.py#L35-L50

I've found some githubs links related with the problem. Hope that helps:
* https://github.com/bottlepy/bottle/issues/602
* https://stackoverflow.com/questions/23168292/python-bottle-utf8-path-string-invalid-when-using-app-mount

Regards

**Comment by frodrigo** [comment]
We just switched to python3 this week. And still fixing some issues. I suspected this to not working properly. Can you also try to loggin/logout into osmose-QA, please ?

**Comment by frodrigo** [comment]
This issue is now fixed. Can you test login/logout, please?

**Comment by ivanrome** [comment]
It's fixed.
Thanks @frodrigo
