### ISSUE TITLE
"Issues by user" search is not working properly with special characters i.e. "usérnáme_"

### ISSUE THREAD

**Issue by ivanrome** [osm-fr/osmose-frontend#236]
Hello,

When I go into the menu "Issues by user" and I search myself "Iván_"

I get into this URL : 
[http://osmose.openstreetmap.fr/es/byuser/?username=Iv%C3%A1n_#](http://osmose.openstreetmap.fr/es/byuser/?username=Iv%C3%A1n_#)
and shows my username with a codification problem "IvÃ¡n_" and shows no issues (that's not true). The search dows not work.

But, If it get into this URL manually
[http://osmose.openstreetmap.fr/es/byuser/Iv%C3%A1n_](http://osmose.openstreetmap.fr/es/byuser/Iv%C3%A1n_) it works

It seems there is a problem with the url to do the search.
Could you please fix this?

**Comment by frodrigo** [comment]
Thank for report.
Fixed by https://github.com/frodrigo/osmose-frontend/commit/84add683f324bd806bfe14e338796bfa82f6438b
