### ISSUE TITLE
wrong/incomplete default comment

### ISSUE THREAD

**Issue by speedbiker** [osm-fr/osmose-frontend#238]
Using osmose as a quality insurance tool of OSM-data I've found 2 mistakes in the saving menue:

- For English version default text the in field comment should be: Fix**ed** with Osmose instead of Fix with Osmose. 
- Same in German: instead of _Mit Osmose reparieren_ it should be filled with _Mit Osmose reparier**t**_

Just to ensure the correct grammar.

**Comment by frodrigo** [comment]
Thank for report. Fixed.

**Comment by speedbiker** [comment]
Ok, thanks for this note. When will this bug-fix be implemented on the OSMOSE-Website? Currently still the old/previous version is online.

**Comment by frodrigo** [comment]
It should be for for english. For other when the translation would be updated. cc @jocelynj

**Comment by speedbiker** [comment]
No, it's neither shown for English nor in German. See attached screenshot, taken a couple minutes ago.
 #
![Bildschirmfoto 2020-04-11 um 10 46 59](https://user-images.githubusercontent.com/13400616/79039488-db942a80-7be1-11ea-90e1-38b1b5869cd4.png)

**Comment by frodrigo** [comment]
Ok. Fixed now. There was two places to fix the default comment.

**Comment by speedbiker** [comment]
Again, there is a problem in **German** translation: the English wording "Fixed with Osmose" is displayed as a default. See uploaded screenshot.
Please revise the German version correctly to: _Mit Osmose repariert_.
![Bildschirmfoto 2020-04-12 um 09 43 05](https://user-images.githubusercontent.com/13400616/79063453-0cd42f80-7ca2-11ea-9e49-520c01217c62.png)

**Comment by frodrigo** [comment]
The German translation is fixed, but not deployed yet. Please be patient, this project is run by volunteers only.

**Comment by frodrigo** [comment]
The translation is now merged on transifex. It will be deployed on next translation update.

**Comment by speedbiker** [comment]
I have to claim another, additional issue concerning translations. Please see screenshot.
Several times I observed a mixture of English and German language on osmose.

**Comment by speedbiker** [comment]
I cannot upload the screenshot now. Why this? filesize only around 500kB.

**Comment by frodrigo** [comment]
There is mix when the translation is not done or not up to date.
You can help on transifex: https://www.transifex.com/openstreetmap-france/osmose/language/de/

**Comment by speedbiker** [comment]
I do not think, translation is wrong, but the site does not load properly. When I click on the field "Change language" and then German, it's correctly displayed.

**Comment by frodrigo** [comment]
So, you hit this https://github.com/osm-fr/osmose-frontend/issues/141

**Comment by speedbiker** [comment]
Yes, in fact it seems to be a similar issue.

**Comment by speedbiker** [comment]
I saw, it was deployed in German language too. But thee is a mistake in wording, obviously a mistake in typing.
Currently it's written: "Mit Osmose reparier**en**t" but it should be (as written above): "Mit Osmose repariert". The characters "**en**" are wrong. Please correct. Take my wording via copy & paste and the problem is solved.
