### ISSUE TITLE
Fix-josm broke

### ISSUE THREAD

**Issue by JacLavi** [osm-fr/osmose-frontend#239]
In Osmose a click on link on "fix-josm" do not open a window in JOSM.  oppositetly a click on "josm-zone" worls as expected.

JOSM 16239

**Comment by Marc-marc-marc** [comment]
fix-josm url is strange
http://localhost:8111/import?url=http://localhost:20009/api/0.3beta/issue/...
instead of
http://localhost:8111/import?url=http://osmose.openstreetmap.fr/api/0.3beta/issue/...

**Comment by frodrigo** [comment]
Fixed.
