### ISSUE TITLE
No marker displayed for users on Firefox under Debian 

### ISSUE THREAD

**Issue by bagage** [osm-fr/osmose-frontend#24]
Using Iceweasel 43.0.4 on Debian sid, there are no markers at all on osmose when using username=XX URL parameter?

For instance opening [this URL](http://osmose.openstreetmap.fr/fr/map/#username=RoPP) shows nothing. It still works fine with Chromium (Chrome) and epiphany (basic Gnome browser): multiple markers near Grenoble appear.

**Comment by jocelynj** [comment]
That's strange. I tried this url, which shows errors on Iceweasel: http://osmose.openstreetmap.fr/en/map/#zoom=14&lat=45.06433&lon=5.69048&item=4110&level=2&username=RoPP&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT

And your link shows errors around Grenoble.

**Comment by frodrigo** [comment]
Please, can you confirm you still have the problem ?

**Comment by frodrigo** [comment]
See also https://github.com/osm-fr/osmose-backend/issues/88

**Comment by bagage** [comment]
No, issue has been fixed thanks!
