### ISSUE TITLE
export josm fail : missing "objects"

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-frontend#241]
from https://osmose.openstreetmap.fr/fr/map/#item=8410&zoom=18&lat=48.619445&lon=-4.555609&level=3&tags=&fixable=
export / josm
erreur "Les clés suivantes sont obligatoires mais n'ont pas été fournies: objects"

**Comment by frodrigo** [comment]
You cannot load new object into JOSM using Osmose export.
