### ISSUE TITLE
Reapearing symbols on Firefox

### ISSUE THREAD

**Issue by fnordson** [osm-fr/osmose-frontend#242]
![FDECGLMGHT](https://user-images.githubusercontent.com/5624605/80258155-cfe54100-8682-11ea-95b9-07ec905ccbfc.gif)

Since I had to "click away" several nodes in an area (several roads were not connected, I made the connection and just had to click away all other ways) I realized the problem seen above. On zooming, nodes would reappear. 
They only stay hidden if you wait longer after clicking them away. 

I'm on Windows with Firefox 75.0

**Comment by frodrigo** [comment]
I see there is no more marker, it may be temporary problem, cache, network, serveur....
