### ISSUE TITLE
API : route for listing classes

### ISSUE THREAD

**Issue by PanierAvide** [osm-fr/osmose-frontend#246]
Is there any way with current API to list classes associated to one or all items ?

Use case is the following : in Pic4Review, we want to create missions for only certains shops from SIRENE. As classes are used to differenciate shops, allowing user to choose which class should be used is a plus. For that, we need to display a select field showing each class associated to a certain item, preferably with translations. An URL like https://osmose.openstreetmap.fr/api/0.3beta/items/8310/class would be very helpful.

**Comment by frodrigo** [comment]
All the classes are available at:
https://osmose.openstreetmap.fr/api/0.3beta/items

**Comment by PanierAvide** [comment]
Thanks :+1:
