### ISSUE TITLE
API v0.3 beta : partial results if bbox is given

### ISSUE THREAD

**Issue by PanierAvide** [osm-fr/osmose-frontend#247]
I have a very weird behaviour with API v0.3 beta, when fetching SIRENE shops (hairdresser class) :

With a BBox parameter (which covers metropolitain France including Corse), it gives 14 results :
`https://osmose.openstreetmap.fr/api/0.3beta/issues?item=8310&limit=10000&status=open&full=true&class=9600201&bbox=-5.45,41.26,9.82,51.30`

Corresponding map for this class shows that there are more than 14 results :
`http://osmose.openstreetmap.fr/fr/map/#item=8310&class=9600201&zoom=7&lat=46.705&lon=2.471&level=1%2C2%2C3&tags=&fixable=`

If I call API without BBox, I have 2268 results (and as it's SIRENE analyser, they are all in France) :
`https://osmose.openstreetmap.fr/api/0.3beta/issues?item=8310&limit=10000&status=open&full=true&class=9600201`

I don't know if it's a comeback of #171 or unrelated.

**Comment by frodrigo** [comment]
There an optimisation when querying with bbox: https://github.com/osm-fr/osmose-frontend/blob/master/modules/query.py#L137-L143
It got a z8 tile.

**Comment by frodrigo** [comment]
The right way to access it is with Osmose `country`
http://osmose.openstreetmap.fr/api/0.3beta/countries
Prefix is usable in query `country=france_*`.

**Comment by PanierAvide** [comment]
OK, thanks for the explanation. However, user input in Pic4Review is a drawn bounding box as now (might change in the future). Is there any way to ask using a bbox but retrieving full result ? As it is now, result is quite confusing (limit is OK, bbox is OK, but we get a subset of results and API answers doesn't give hint about this mechanism).

**Comment by PanierAvide** [comment]
Or maybe another solution would be to give associated bbox (or more precise limit) of countries and sub-countries to let user select which one suits best its need. But makes reuse a lot more complex.

**Comment by frodrigo** [comment]
The data is indexed by tiles.
The tile corresponding to your bbox is 0/0/0, so the whole world. We cannot honour a such query.

I see 2 solutions:
* adding a spatial index (but we already remove it)
* get all data from all corresponfing z8 tiles (but we ca try to move to lower zoom), this can be done from outside or inside of osmose.

I start by looking at the cost of a spatial index.

**Comment by PanierAvide** [comment]
Note that the given initial example is for France, but I had same behaviour with a more restricted bbox (only covering Bretagne) : only ~15 features even if there are more than that in Osmose. Getting aggregated results from several tiles from Osmose API could be a good solution (even if some features are outside initial BBox).

**Comment by frodrigo** [comment]
* With the current implementation you will get les results, while the bbox does not feet in a z8 tile.
* There a secondary filter to ensure the bbox is respected.

**Comment by PanierAvide** [comment]
OK, understood :-)

**Comment by frodrigo** [comment]
Spatial index is acceptable. `item` must be provided to use it.

It is deployed (for test).

**Comment by PanierAvide** [comment]
It seems to work as expected, and offers good performance on client side. Thanks ! :smiley:  We can now create missions in Pic4Review for item and specific classes from Osmose, like this one for hairdressers : https://pic4review.pavie.info/#/mission/1025
