### ISSUE TITLE
error due to bottle version in requirements.txt

### ISSUE THREAD

**Issue by fansanelli** [osm-fr/osmose-frontend#248]
Hello,

I experienced this problem:

https://github.com/bottlepy/bottle/issues/1115

is there a reason to now upgrade bottle?
Thanks
Francesco

**Comment by frodrigo** [comment]
Yes we can try an update. Since we move to py3 I think It will be easier.

**Comment by frodrigo** [comment]
The plan is now to replace bottle by fast api.
