### ISSUE TITLE
remove old analyse 

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-frontend#25]
old analyse australia show 280 erros without issues
http://osmose.openstreetmap.fr/en/errors/?source=16010&item=1230&class=1

**Comment by jocelynj** [comment]
Thanks. It is now fixed - tables dynpoi_class and dynpoi_update_last weren't correctly cleaned.

**Comment by didier2020** [comment]
idem for old analyse slovakia 
http://osmose.openstreetmap.fr/fr/errors/?country=slovakia*&item=1230
thanks
