### ISSUE TITLE
enhance docker documentation

### ISSUE THREAD

**Issue by fansanelli** [osm-fr/osmose-frontend#250]
Hello,

I'm trying to run osmose-frontend in docker...
Without the:

"--rm frontend"

parameter I get:

> ERROR: Cannot create container for service frontend: Conflict. The container name "/frontend" is already in use by container "4f5afe52050c51393509163c256e3389a2a8cb2a87a68cc20ae65468f9cfdf52". You have to remove (or rename) that container to be able to reuse that name.

and when I try to access the db I get:

> root@7f64a66bc258:/data/project/osmose/frontend# psql -h postgres osmose_frontend osmose
> perl: warning: Setting locale failed.
> perl: warning: Please check that your locale settings:
> 	LANGUAGE = (unset),
> 	LC_ALL = (unset),
> 	LANG = "en_US.UTF-8"
>     are supported and installed on your system.
> perl: warning: Falling back to the standard locale ("C").
> psql: could not translate host name "postgres" to address: Name or service not known
> 

as mentioned I also have to run

> pip install -U bottle

in order to run 

> ./osmose-standalone-bottle.py

without errors.

Can you please give some advice / update docs?

Thanks
Francesco

**Comment by frodrigo** [comment]
I update the doc, this missing part of the doc was know bit not fixed, yet.

Review 940faf8  and 1ca022c.

**Comment by fansanelli** [comment]
Thanks! I'll give a try tomorrow
