### ISSUE TITLE
On issues list page, some countries are missing in the selector

### ISSUE THREAD

**Issue by pyrog** [osm-fr/osmose-frontend#252]
* canada
* china
* czech_republic
* germany
* india
* italy
* japan
* netherlands
* poland
* russia
* spain
* united_kingdom
* usa

New Zealand have only one "region": new_zealand_tokelau

Related to #251

**Comment by frodrigo** [comment]
Since it is no a list countries in the world but countries define in Osmose configuration, there is no missing area.
