### ISSUE TITLE
Link to the correct repository in the "Welcome to Osmose-QA" tab

### ISSUE THREAD

**Issue by wetneb** [osm-fr/osmose-frontend#256]
The "Welcome to Osmose-QA" tab says:

> Feel free to report problem, idea or new OpenData you want to add to Osmose on our Github.

Why not add a link there? I understand the correct repository to use depends on the type of issue (frontend or backend) but that could probably be made more precise in the text?

I feel like there should be some sort of link there, perhaps just to https://github.com/osm-fr if you do not want to point to a specific repository.

**Comment by frodrigo** [comment]
Thank for report fixed.
