### ISSUE TITLE
Get graph.png data as CSV or JSON ?

### ISSUE THREAD

**Issue by PanierAvide** [osm-fr/osmose-frontend#259]
Hello,

Is there a way to retrieve historical changes for an item, like it's done by calling `graph.png`, but as raw data (like CSV or JSON) ? [We are working on a dashboard](https://github.com/vdct/ProjetDuMois) to encourage contributing on Osmose tasks, having access to this kind of raw data would allow :
- Clean / interactive display of data on third-party websites
- Various analysis / aggregation of data

Best regards.

**Comment by frodrigo** [comment]
We have other format like svg, but no raw data. 

It should be easy to add.

**Comment by PanierAvide** [comment]
Adding this feature might be easy, but I'm unable to generate existing graph.png with fronted running on Docker :
```
psycopg2.errors.UndefinedTable: relation "stats" does not exist
```

I'm trying to run by myself `schema.sql` file, but it still lacks `dynpoi_stats` table, which I can't find `CREATE TABLE` anywhere in frontend code.

**Comment by frodrigo** [comment]
The table `dynpoi_stats` was replaced by `stats`, but not in the export script.

**Comment by PanierAvide** [comment]
Great, thanks for the fix. I will give it a try tomorrow, but can you reopen the issue for the original question of getting graph data as CSV/JSON ?

**Comment by PanierAvide** [comment]
Thanks, it now works as expected, and I was enable to offer a PR :smile:
