### ISSUE TITLE
Polish language name

### ISSUE THREAD

**Issue by endro** [osm-fr/osmose-frontend#26]
Hey, Can you correct name of polish language?

In tools/utils.py#28, from
`languages_name["pl"] = u"Polszczyzna"`
to
`languages_name["pl"] = u"Polski"`

**Comment by jocelynj** [comment]
That's strange - Polszczyzna is what I found when trying to find an appropriate word. Do both words mean the same thing ?

**Comment by endro** [comment]
Yes, but Polszczyzna is rather used by linguists, humanists.
