### ISSUE TITLE
Link ref:UAI for school broken

### ISSUE THREAD

**Issue by Percherie** [osm-fr/osmose-frontend#264]
Hello,

On the Osmose notes, the link to the page corresponding to the IAU code of the schools is broken.

For example: https://www.education.gouv.fr/pid24302/annuaire-resultat-recherche.html?lycee_name=0110359F

**Comment by frodrigo** [comment]
Need to look tag2link if can be fixed.
But tag2link is now deprecated.

**Comment by deuzeffe** [comment]
Ok. But https://github.com/osm-fr/osmose-frontend/issues/230#issuecomment-1110857831
So?

**Comment by frodrigo** [comment]
Switch to new tag2link
https://github.com/JOSM/tag2link
