### ISSUE TITLE
class link doesn't remember country

### ISSUE THREAD

**Issue by thibaultmol** [osm-fr/osmose-frontend#274]
Hi,

When I'm on this page
 http://osmose.openstreetmap.fr/en/errors/?country=belgium_flanders&item=xxxx&level=1%2C2%2C3
and I click on a class id.
The page it directs me to is correct but it doesn't have the country set anymore.
http://osmose.openstreetmap.fr/en/errors/?item=9001&class=9001001

While I feel like it would make sense for it to show all the errors of that class for the country I was already filtering on 

https://www.whatsmybrowser.org/b/5RDDX

Cheers

**Comment by frodrigo** [comment]
Done for item and class.
