### ISSUE TITLE
use black to format python code

### ISSUE THREAD

**Issue by NoemiNahomy** [osm-fr/osmose-frontend#275]
I propose to use [black](https://pypi.org/project/black/) to format python code and and add this library to requirements.
What do you think ?

**Comment by frodrigo** [comment]
For now, I'm not pro automatic code formatting on this project. As first step we try to align on backend code quality standard: https://github.com/osm-fr/osmose-backend/blob/master/pylama.ini#L3

**Comment by frodrigo** [comment]
Done, as well as isort, flak8, and soon mypy.
