### ISSUE TITLE
fix-josm produce a "nothing to upload" layer

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-frontend#276]
- open josm without any layer
- open https://osmose.openstreetmap.fr/fr/map/#item=8410&zoom=18&lat=47.053933&lon=-0.185255&level=1%2C2%2C3
- clic on the marker
- clic on the fix-josm
- in josm, the new node is well present in the layer
- in josm, the upload button remains gray as if the layer did not contain any data to send to osm.
if it's not an problem on the osmose side, I'll open a josm ticket so that they have the debug information.

**Comment by frodrigo** [comment]
Same here. Report to JOSM.

**Comment by Marc-marc-marc** [comment]
https://josm.openstreetmap.de/ticket/19816

**Comment by Marc-marc-marc** [comment]
feedback from @Don-vip in https://josm.openstreetmap.de/ticket/19816#comment:1
> Shouldn't the osmose file simply include action=modify?

**Comment by frodrigo** [comment]
`data["action"] = "modify"` is already here for fix, only missing on object creation.

**Comment by frodrigo** [comment]
Done, but not working.

**Comment by Marc-marc-marc** [comment]
reply https://josm.openstreetmap.de/ticket/19816#comment:3

**Comment by Marc-marc-marc** [comment]
patch by simon04 (josm), I'll test it soon

**Comment by frodrigo** [comment]
@Marc-marc-marc can we close this one now?

**Comment by frodrigo** [comment]
Fixed on JOSM.
