### ISSUE TITLE
Changing the language

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-frontend#277]
When I change the language of Osmose from one to another, the titles of the issues are still in other language, here: Polish.

![Osmose-language](https://user-images.githubusercontent.com/57260466/94200633-01c13480-febb-11ea-82fa-ba45865132fb.png)

**Comment by frodrigo** [comment]
Yes, its is a know "feature". The new version of the API deals in a different way with languages, but the frontend does not have the right implementation for it. So part coming from the API use the default language of the browser.

**Comment by frodrigo** [comment]
Fixed as side effect of the new version.
