### ISSUE TITLE
Vector tiles : 404 has no CORS headers in response

### ISSUE THREAD

**Issue by PanierAvide** [osm-fr/osmose-frontend#278]
Hello,

We use with Mapbox GL the Osmose tiles on projetdumois.fr. When a vector tile has no data, current code send a HTTP 404 status. But the response doesn't contain any CORS header, making client span a lot of errors :

![Capture d’écran_2020-09-29_09-08-59](https://user-images.githubusercontent.com/1349014/94524818-6d94fb80-0233-11eb-8426-44a5d840eeaa.png)

Example request : https://osmose.openstreetmap.fr/api/0.3/issues/10/504/352.mvt?item=8370&country=france*

HTTP response headers :

```
HTTP/2 404 Not Found
server: nginx/1.19.1
date: Tue, 29 Sep 2020 07:09:25 GMT
content-type: text/plain
content-length: 0
X-Firefox-Spdy: h2
```

Would it be possible either :
- To send a valid tile (200) status but with an empty list of features
- Or to add CORS headers in HTTP response ?

Best regards.

**Comment by frodrigo** [comment]
The right thing to do is to send a "204 No Content".
https://github.com/osm-fr/osmose-frontend/blob/master/api/issues_tiles.py#L123
