### ISSUE TITLE
Displaying results of osmlint

### ISSUE THREAD

**Issue by planemad** [osm-fr/osmose-frontend#28]
@jocelynj osmose is the best tool I have seen so far for OSM QA errors! 

Is it possible to add a new category for errors generated using [osmlint](https://github.com/osmlab/osmlint)? The output is a geojson file in [this format](https://gist.github.com/d0e3878b1457a52928b7). Right now the output is filtered for a certain set of users, but we can generate a global one rather easily.

Backstory: https://github.com/osmlab/osmlint/issues/60

**Comment by frodrigo** [comment]
I already see this project. But I think there is not to munch interesting issues class produced by osmlint. Only bridgeonnode and missinghighwaysus are not already present in Osmose (or OSMI), bridgeonnode is so simple to recode and only missinghighwaysus is on finally interesting.

**Comment by planemad** [comment]
Adding missinghighwaysus will be awesome! What would be the preferred format to make it easy to use in osmose?

**Comment by frodrigo** [comment]
Need build a geojson to [xml](http://wiki.openstreetmap.org/wiki/Osmose#Issues_file_format) converter and upload the result to osmose-frontend.
But the result USA mbtile is around 2Gb...
