### ISSUE TITLE
JOSM direct link for relation is broken in user view

### ISSUE THREAD

**Issue by Mannivu** [osm-fr/osmose-frontend#283]
While in the "Issue by user" view, the JOSM direct link for a relation is broken due to a double `/` in link. For example in this row
![image](https://user-images.githubusercontent.com/42747216/95778753-095d4780-0cc9-11eb-9ffb-722fc8efca3a.png)
the (j) link for the r11288145 is this https://osmose.openstreetmap.fr/en/josm_proxy?import?url=https://www.openstreetmap.org//api/0.6/relation/11288145/full
while it should have only one `/` between `openstreetmap.org` and `api`: https://osmose.openstreetmap.fr/en/josm_proxy?import?url=https://www.openstreetmap.org/api/0.6/relation/11288145/full

**Comment by frodrigo** [comment]
Fixed
