### ISSUE TITLE
Export on invalid lat/lon

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-frontend#288]
On export, return valide data on invalid lat/lon by doing a modulo

eg. https://osmose.openstreetmap.fr/en/map/#zoom=12&lat=13.4766&lon=504.818

from #154

**Comment by Korgi2** [comment]
Actually I think this can be better states as "Osmose map doesn't wrap around lat/lon and instead continuously grows it." If you go around the edge of the world to the other side instead of resetting it just keeps adding.

**Comment by Korgi2** [comment]
![image](https://user-images.githubusercontent.com/61196219/100929653-f8090e00-34b5-11eb-9c74-b4fcfe986946.png)

**Comment by frodrigo** [comment]
Need module here to be in the right range
https://github.com/osm-fr/osmose-frontend/blob/master/modules/query.py#L143
