### ISSUE TITLE
Export URLs are not updated when panning or zooming

### ISSUE THREAD

**Issue by gileri** [osm-fr/osmose-frontend#292]
[They](https://github.com/osm-fr/osmose-frontend/blob/b57b40e1aa2d67fcec07b97045be29d01c58f062/web/static/map/Osmose.Export.js) get updated when [interacting with the Menu](https://github.com/osm-fr/osmose-frontend/blob/b57b40e/web/static/map/Osmose.Menu.js#L158), but not while panning or zooming the map.

**Comment by frodrigo** [comment]
Fixed as side effect of new version.
