### ISSUE TITLE
docker : wrong frontend url in "fix-josm" link

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-frontend#294]
the frontend fix-josm http://localhost:20009/fr/josm_proxy?import?url=http://osmose.openstreetmap.fr/api/0.3/issue/<ID>
fail to work, because it ask josm to ask the main frontend and not the local one

**Comment by frodrigo** [comment]
You can set it with `URL_FRONTEND` or use `docker-compose-test.yml`.

**Comment by Marc-marc-marc** [comment]
i'm already using docker-compose-test.yml, the full commande line i'm using is
`docker-compose -f docker-compose.yml -f docker-compose-test.yml -f docker-compose-dev.yml run --name frontend -p 20009:20009 frontend`
found at https://github.com/osm-fr/osmose-frontend/tree/master/docker#docker-for-development
any improvement to avoir the need to set URL_FRONTEND by hand ?

**Comment by Marc-marc-marc** [comment]
thanks.
impossible to reproduce, I close the ticket and will reopen it if it happens again
