### ISSUE TITLE
Information on issue: Invalid link to source code

### ISSUE THREAD

**Issue by kudlav** [osm-fr/osmose-frontend#301]
Look at this page:  
https://osmose.openstreetmap.fr/cs/error/800658ad-781c-d832-5e38-daab6ab42ebe

At the bottom of marker section there is link to _source code_.

The link should be:  
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Highway_Lanes.py#L54  
Actually it is:  
[__https://osmose.openstreetmap.fr/en/error__/https://github.com/osm-fr/osmose-backend/blob/master/plugins/Highway_Lanes.py#L54](https://osmose.openstreetmap.fr/en/error/https://github.com/osm-fr/osmose-backend/blob/master/plugins/Highway_Lanes.py#L54)  

Which is invalid.

**Comment by frodrigo** [comment]
Ok, Fixes this one and all other links to the map.
