### ISSUE TITLE
RSS feed is broken?

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-frontend#303]
RSS feed is broken?

404

http://osmose.openstreetmap.fr/en/errors.rss?zoom=18&item=0000%2C1010%2C1040%2C1050%2C1060%2C1080%2C1090%2C1100%2C1110%2C1140%2C1150%2C1160%2C1170%2C1180%2C1190%2C1200%2C1210%2C1220%2C1221%2C1230%2C1240%2C1250%2C1270%2C1280%2C2xxx%2C3xxx%2C4020%2C4040%2C4060%2C4061%2C4070%2C4080%2C4090%2C4100%2C4110%2C4130%2C6xxx%2C7010%2C7011%2C7012%2C7020%2C7050%2C7051%2C7060%2C7070%2C7080%2C7090%2C7100%2C7110%2C7120%2C7130%2C7140%2C7150%2C7160%2C7170%2C7190%2C7220%2C7240%2C8010%2C8011%2C8012%2C8020%2C8021%2C8022%2C8025%2C8026%2C8030%2C8031%2C8032%2C8040%2C8041%2C8042%2C8050%2C8051%2C8060%2C8070%2C8080%2C8110%2C8120%2C8121%2C8122%2C8130%2C8131%2C8132%2C8140%2C8150%2C8160%2C8161%2C8162%2C8170%2C8180%2C8190%2C8191%2C8192%2C8200%2C8201%2C8202%2C8210%2C8211%2C8221%2C8230%2C8240%2C8250%2C8260%2C8270%2C8280%2C8281%2C8290%2C8320%2C8330%2C8331%2C8340%2C8341%2C8350%2C8351%2C9000%2C9001%2C9002%2C9003%2C9004%2C9005%2C9006%2C9007%2C9009%2C9010%2C9014%2C9015%2C9016%2C9100&level=1%2C2&tags=&fixable=&limit=500&bbox=-75.77596664428712%2C45.31232182518018%2C-75.52310943603517%2C45.41447897237767

**Comment by frodrigo** [comment]
Thank you for reporting.
We are doing lot of changes under the wood. And break this redirection.
It is now fixed.
Other bug on non map pages may be here.
