### ISSUE TITLE
Frontend docker image creation fails during npm build

### ISSUE THREAD

**Issue by nuxper** [osm-fr/osmose-frontend#304]
I followed instructions to build the frontend:
```
curl http://osmose.openstreetmap.fr/export/osmose-menu.sql.bz2 | bzcat > osmose-menu.sql
docker-compose build

```
It fails during npm build:
```
ERROR in ./static/app/i18n.js
Module not found: Error: Can't resolve '../../po' in '/data/project/osmose/frontend/web/static/app'
```
Full log attached
[osmose-frontend-docker-compose-build.log](https://github.com/osm-fr/osmose-frontend/files/5953881/osmose-frontend-docker-compose-build.log)

I suppose the issue is in the Dockerfile because the po folder is not added yet when the npm run build is started. Should the whole frontend folder be added _before_ the npm run build ? This seems to work on my workspace

```
#ADD ./web/static /data/project/osmose/frontend/web/static
ADD . /data/project/osmose/frontend
RUN cd web && npm run build
#ADD . /data/project/osmose/frontend
```

**Comment by frodrigo** [comment]
Thank you for report. Fixed.
Note we are making large changes, and other bugs may be expected.
