### ISSUE TITLE
https://osmose.openstreetmap.fr/en/control/update is spinning forever

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-frontend#306]
Reported by someone else:

> When I try to load https://osmose.openstreetmap.fr/en/control/update it pretty much kills my browser and computer. Cpu and memory usage skyrocket. Same thing happens in firefox, chrome and edge

I opened on Firefox 85.0.1, nothing appeared for long time except for browser warning about long running script.

**Comment by mxxcon** [comment]
Chrome 88. Fresh session with just a single tab open, after waiting for about a minute memory usage is 3.1GB and continues to climb.

**Comment by frodrigo** [comment]
We just switched this part of the Osmose Frontend to Vue JS and this page and http://osmose.openstreetmap.fr/en/control/update_matrix take more time than before.
We know that /control/update is too big to be displays using Vue JS.

What do you use this page for?

We does not use it, and was thinking about to remove it.
There is other control pages
http://osmose.openstreetmap.fr/fr/control/update_matrix
http://osmose.openstreetmap.fr/fr/control/update_summary
http://osmose.openstreetmap.fr/fr/control/update_summary_by_analyser

**Comment by mxxcon** [comment]
Since that page never loads for me I don't know what's on it so I don't know what I can use it for :) 
I guess it shows which part of the map got updated?

**Comment by frodrigo** [comment]
It is a raw list of 58 096 row of analyser x area with last update timestamp. You have the same in the matrix.

**Comment by matkoniecz** [comment]
> What do you use this page for?

I never used, someone (maybe @mxxcon ?) complained on Discord that it is broken so I forwarded it here.

> It is a raw list of 58 096 row of analyser x area with last update timestamp. You have the same in the matrix.

I am not going to use it, display of errors on maps is ideal for my purposes.

**Comment by frodrigo** [comment]
Removed
