### ISSUE TITLE
Opening JOSM validator folder is not opening it

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-frontend#309]
To reproduce:

visit http://osmose.openstreetmap.fr/en/map/#zoom=8&lat=50.391&lon=8.959&item=xxxx&level=1&tags=&fixable=

scroll down on error list in sidebar - try to open/close JOSM folder

Unlike other folders no sublist is shown. I am pretty sure that it used to.

I disabled adblock and flushed browser cache.

Firefix 86.0 on Lubuntu.

![screen04](https://user-images.githubusercontent.com/899988/110112703-62ca2e00-7db2-11eb-9839-7a8f8b6c2bde.png)

**Comment by frodrigo** [comment]
You have a level=1 filter. On level 1, there is nothing into JOSM validator categorie.

**Comment by matkoniecz** [comment]
Whoops, sorry.
