### ISSUE TITLE
links in column # useless

### ISSUE THREAD

**Issue by malenki** [osm-fr/osmose-frontend#31]
On http://osmose.openstreetmap.fr/de/byuser/?username=malenki there is a column named "#".
It has links looking like this:
http://osmose.openstreetmap.fr/de/byuser/?item=2020
The page behind that link looks this way:
![2016-04-16_003202_scr](https://cloud.githubusercontent.com/assets/188565/14576595/b534a020-036a-11e6-964b-94cc134233a7.png)

When I enter my user name I am on the page where I started from…

**Comment by dex2000** [comment]
i can confirm this

**Comment by jocelynj** [comment]
Hum, interesting… This link should instead point to http://osmose.openstreetmap.fr/de/byuser/?username=malenki&item=2060
