### ISSUE TITLE
limit=1 produce wrong total

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-frontend#311]
https://osmose.openstreetmap.fr/fr/errors/?item=2090&class=1&country=france* total 1594
I used to add  &limit=1 when I don't need a list of all issues but only the total, but 
https://osmose.openstreetmap.fr/fr/errors/?item=2090&class=1&country=france*&limit=1 total 131
it look like it's only the total of the first "contry=" found

**Comment by frodrigo** [comment]
https://osmose.openstreetmap.fr/fr/errors/?item=2090&class=1&limit=2

Limit also limit the first table. It should not.

**Comment by frodrigo** [comment]
Show upper block only with item

**Comment by frodrigo** [comment]
Fixed.
