### ISSUE TITLE
Database initialisation

### ISSUE THREAD

**Issue by archie83** [osm-fr/osmose-frontend#315]
Hi,
I have installed osmose-frontend by following this guide:
https://github.com/osm-fr/osmose-frontend/blob/master/INSTALL.md

But I have a problem with the database, it seems that it is not fully initialised. For example, the tables "items" and "categories" are empty.

Did I forget something, or is there an instruction that is missing in the guide?

**Comment by frodrigo** [comment]
Follow this if you want the same menu as on osmose.openstreetmap.fr :
* curl http://osmose.openstreetmap.fr/export/osmose-menu.sql.bz2 | bzcat > osmose-menu.sql
* https://github.com/osm-fr/osmose-frontend/blob/master/docker/postgres-init.sh

**Comment by archie83** [comment]
Thank you. Could you update INSTALL.md?

**Comment by frodrigo** [comment]
This way of installing is no more really maintained (use Docker in place). But we take PR anyway.
