### ISSUE TITLE
"fix-josm" doesnt work anymore

### ISSUE THREAD

**Issue by dex2000** [osm-fr/osmose-frontend#319]
for example:
http://osmose.openstreetmap.fr/de/map/#country=germany_thueringen&item=8320%2C8360&level=1%2C2%2C3&zoom=18&lat=50.734385&lon=11.820232&issue_uuid=fbcba42a-ecb4-1cc2-5d5c-f2c200fdfa18

Click on "fix-josm" in the popup doesnt work. Error-console says: "400 bad request"

**Comment by zorglubu** [comment]
The string "https:" seems to be missing in the link. Copying the link and adding this string after "import?url=" solve the problem.

**Comment by didier2020** [comment]
this change ?
https://github.com/osm-fr/osmose-frontend/commit/854796e0c782714d0a6b876b2d619b4fa56dd266

**Comment by zorglubu** [comment]
Thank you !  :-)

**Comment by dex2000** [comment]
thx!
