### ISSUE TITLE
Obsolete string in osmose-frontend.pot

### ISSUE THREAD

**Issue by kcwu** [osm-fr/osmose-frontend#32]
I found there are lots of obsolete strings still in pot file. For example,
`"Error reported on: "` was replaced by `"Issue reported on: "`.
But `"Error reported on: "` is still in https://github.com/osm-fr/osmose-frontend/blob/master/po/osmose-frontend.pot#L515

If looking at https://github.com/osm-fr/osmose-frontend/blob/master/po/osmose-frontend.pot, you can find lots of strings without line numbers. They are no longer appearing in the code.

I guess they are there because you pass `--join-existing` to `xgettext`.
https://github.com/osm-fr/osmose-frontend/blob/master/po/Makefile#L21

The typical way to handle obsolete strings in pot is making them commented out. https://www.gnu.org/software/gettext/manual/gettext.html#Obsolete-Entries
By doing so, translators don't need to translate them and translation tools can still reference them (as hints to translate new strings).

Otherwise, translators would waste time to translate those obsolete strings.

**Comment by jocelynj** [comment]
I've added --join-existing so that xgettext didn't re-order translations. I thought that it would make it simpler to check what new translations were added. But you're right that it keeps old translations that are irrelevant.

Maybe the best way to handle this is to remove --join-existing - I will think about that.

**Comment by jocelynj** [comment]
I have manually removed the no-longer relevant strings from osmose-frontend.pot and osmose-backend.pot. There shouldn't be any obsolete strings now.
