### ISSUE TITLE
Disable issue item directly from issue popup and/or item help

### ISSUE THREAD

**Issue by bagage** [osm-fr/osmose-frontend#320]
By default all items are checked. When you want to remove an item (because not interested in it), you have to search it in the long list on the left side.

It would be great if either instead:

1. You could disable it from an issue popup (via a fourth button for instance)
2. In right-side item help panel 

Something like that for instance (see :eye: buttons):

![image](https://user-images.githubusercontent.com/1451988/114271705-0db5b380-9a13-11eb-8ac7-b1a4d9d8d1ad.png)

**Comment by frodrigo** [comment]
Also possible to disable the item with a checkbox on popup title.
