### ISSUE TITLE
Vue is in development mode

### ISSUE THREAD

**Issue by bbigras** [osm-fr/osmose-frontend#323]
> You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html

**Comment by frodrigo** [comment]
It build using 

https://github.com/osm-fr/osmose-frontend/blob/master/web/package.json#L60

How do you see Vue JS is deployed on development mode?

**Comment by bbigras** [comment]
In the devtools' console:

![image](https://user-images.githubusercontent.com/24027/114564130-93c63a00-9c5f-11eb-9bb0-cc4806517989.png)

**Comment by frodrigo** [comment]
Webpack mode is production, but not Vue JS.

Any help welcome.

cc @fansanelli

**Comment by bbigras** [comment]
Try setting `NODE_ENV=production`.

https://fr.vuejs.org/v2/guide/deployment.html
