### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by bbigras** [osm-fr/osmose-frontend#325]
![image](https://user-images.githubusercontent.com/24027/114467786-eceb8a80-9bd9-11eb-872d-ed3a445e53b6.png)

on Firefox

URL: https://osmose.openstreetmap.fr/en/map/?item=5010#zoom=3&lat=44.9&lon=-37

Maybe my URL is just wrong.

**Comment by frodrigo** [comment]
The URL is not invalid, but it is the cause.

The query part (`?item=50210`) make it fails. It should be in the hash part.

Do you forge the URL your self, or it is from a link ?

**Comment by tuxayo** [comment]
Hi :) Is that related to this? Similar error on a map item:

https://osmose.openstreetmap.fr/map/#&item=8022&zoom=17&lat=43.5828473&lon=6.2754982&level=3&tags=&fixable=&issue_uuid=398c1dfe-5ff8-ef0d-e9eb-7ea057f44978

Firefox: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Chromium: Unexpected token I in JSON at position 0

**Comment by bbigras** [comment]
In my case I think it was related to me being logged and checking the things where you can see problems on nodes you recently modified. I think the item number was set in a cookie.
