### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by bbigras** [osm-fr/osmose-frontend#326]
I can't log in. But I was able earlier today.

![image](https://user-images.githubusercontent.com/24027/114468174-99c60780-9bda-11eb-912c-fc68ebde3517.png)

**Comment by frodrigo** [comment]
Please give more details.

**Comment by bbigras** [comment]
Will do.

Note that I also saw this this morning on `https://www.openstreetmap.org/oauth/authorize?oauth_token=...`
![image](https://user-images.githubusercontent.com/24027/114565669-05eb4e80-9c61-11eb-810a-33616fd0f4ad.png)
