### ISSUE TITLE
maxheight=default

### ISSUE THREAD

**Issue by Tchiller** [osm-fr/osmose-frontend#33]
maxheight=default results in a warning. An example can be found here: http://www.openstreetmap.org/way/264102747
The warning looks like: http://osmose.openstreetmap.fr/en/error/7032379774

Regarding to this page http://wiki.openstreetmap.org/wiki/Key:maxheight, this value should be allowed. 

Thank you!

**Comment by frodrigo** [comment]
Already fixed on backend
