### ISSUE TITLE
RSS item description is hardly readable

### ISSUE THREAD

**Issue by gileri** [osm-fr/osmose-frontend#339]
If I understand correctly it was done to unify the description generation for GPX, KML, and RSS.

[KML](http://docs.opengeospatial.org/is/12-007r2/12-007r2.html#103) and RSS both accept HTML, but not [GPX](https://www.topografix.com/GPX/1/1/#type_wptType). I think it would be best to reintroduce HTML for both KML and RSS descriptions. What do you think ?

**Comment by frodrigo** [comment]
> If I understand correctly it was done to unify the description generation for GPX, KML, and RSS.

It was a quick "win".
It was done to remove xml generating from template. In order to remove then the template engin no more used.

> [KML](http://docs.opengeospatial.org/is/12-007r2/12-007r2.html#103) and RSS both accept HTML, but not [GPX](https://www.topografix.com/GPX/1/1/#type_wptType). I think it would be best to reintroduce HTML for both KML and RSS descriptions. What do you think ?

Yes. If you want to make changes, you can also look at #314 and #155.
