### ISSUE TITLE
Selected items are not correctly read from permalink

### ISSUE THREAD

**Issue by otrichet** [osm-fr/osmose-frontend#34]
When opening a permalink with more than 2 selected items ([example](http://osmose.openstreetmap.fr/fr/map/#zoom=12&lat=50.5457&lon=3.1019&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT&item=8101%2C8110%2C8190&level=1%2C2%2C3&tags=&fixable=)), the selected items are lost.

The bug is in then function L.UrlUtil.queryParse (Permalink.js) where decoreURI() is used instead of decodeURIComponent(). Loading the modified function into the browser console corrects the issue for the session:
```javascript
L.UrlUtil.queryParse: function (s) {
		var p = {};
		var sep = '&';
		if (s.search('&amp;') !== -1)
			sep = '&amp;';
		var params = s.split(sep);
		for (var i = 0; i < params.length; i++) {
			var tmp = params[i].split('=');
			if (tmp.length !== 2) continue;
			p[tmp[0]] = decodeURIComponent(tmp[1]);
		}
		return p;
};
```

Patch sent upstream at https://github.com/shramov/leaflet-plugins/pull/238

**Comment by frodrigo** [comment]
Thank you, now it is effective.
