### ISSUE TITLE
Theme list empty

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-frontend#342]
Hello,

The Theme list is empty (third field on top of the left menu): we can't choose "fix chair" eg or other. Is it just me?

HTH.

**Comment by gileri** [comment]
Same for me on Firefox and Chromium. There is nothing obvious in the console our in XHRs.

**Comment by frodrigo** [comment]
Fixed

**Comment by deuzeffe** [comment]
@frodrigo Check. OK. Thx!
