### ISSUE TITLE
Broken JOSM relation link

### ISSUE THREAD

**Issue by starsep** [osm-fr/osmose-frontend#356]
On https://osmose.openstreetmap.fr/en/byuser/starsep?username=starsep&item=1260
I get this broken JOSM relation link:
https://osmose.openstreetmap.fr/en/josm_proxy?import?url=undefinedapi/0.6/relation/4037547/full

It seems to be an issue at https://github.com/osm-fr/osmose-frontend/blob/6a5a4f0940cfab9db7036c10d91735119d7ce4f4/web/src/components/issues-list.vue#L112

**Comment by frodrigo** [comment]
Looks to be already fixed.
