### ISSUE TITLE
Osmose not loading data in JOSM

### ISSUE THREAD

**Issue by ngumenawesamson** [osm-fr/osmose-frontend#358]
Currently, Osmose error editing is only possible in ID Editor and data cannot load directly in JOSM

**Comment by frodrigo** [comment]
Similary issue already repported. But not the cause.
Try using https inplace of http.

**Comment by ngumenawesamson** [comment]
It looks like when you use https:// it logs you out of osm.org and indicates that the token is invalid
![Screenshot 2022-01-25 114733](https://user-images.githubusercontent.com/29952077/150943021-74c64336-fbe9-4058-a869-05a0293ad1ce.jpg)

**Comment by frodrigo** [comment]
A change have been made. Please can you recheck if it is better for you.
