### ISSUE TITLE
"JOSM edit" in popups can't work when site loaded over https

### ISSUE THREAD

**Issue by grischard** [osm-fr/osmose-frontend#36]
The pop-ups when clicking on an issue contain links to open the problematic object in JOSM, e.g. `http://localhost:8111/load_object?objects=w295284609`.

When osmose is loaded over https, clicking on those links doesn't open the object in JOSM, but produces errors like:

`Mixed Content: The page at 'https://osmose.openstreetmap.fr/en/map/' was loaded over HTTPS, but requested an insecure resource 'http://localhost:8111/load_object?objects=w295284609'. This request has been blocked; the content must be served over HTTPS.`

I'm not sure what the best solution would be, but think I prefer the first one.

- Call https://localhost:8112 if osmose is loaded over https. That's what overpass-turbo does.
- Call https://localhost:8112 always - I'm not sure it's activated by default and that the certificate is always trusted
- Open the josm link in a hidden iframe or img instead of using xmlhttprequest, to bypass that restriction?  We don't care about what JOSM replies anyway, but I'm not sure that would work.
- Let the user set the josm endpoint in a preference

**Comment by frodrigo** [comment]
> Open the josm link in a hidden iframe

It's already the case, maybe is no more enough.

On my JOSM http is not active by default and even active is unsecure.

> Let the user set the josm endpoint in a preference

There is no preferences on Osmose, yet.

**Comment by frodrigo** [comment]
I test the <img> solution, at least it works.

**Comment by grischard** [comment]
Ah, and I'm getting this problem with Chrome 52.

**Comment by jocelynj** [comment]
Would replacing http://localhost:8112 by //localhost:8112 work in all cases ?

**Comment by jocelynj** [comment]
Ok, I understand the issue better: josm is listening on http://localhost:8111 and https://localhost:8112, so the port has to change depending on the configuration. And I confirm that josm is not listening in https by default, and that its certificate is invalid, so I don't think we can enable https by default, as it would break everything without any explanation.

**Comment by grischard** [comment]
Everything is already currently broken without any explanation when you load osmose over https :)

This is why I'm suggesting to call https://localhost:8112 if osmose is loaded over https. That's what overpass-turbo does: https://github.com/tyrasd/overpass-turbo/blob/45d50d1ea63ec268bf0ab44361fb17276a9867fa/js/ide.js#L1434

**Comment by jocelynj** [comment]
@frodrigo: were you able to fix this issue ?

**Comment by frodrigo** [comment]
@jocelynj : yes with an <img> within the iframe or the main body, browser just set warning level and no block the iframe content.

**Comment by frodrigo** [comment]
I do the trick. To be tested with https. only testet with http on localhost.
