### ISSUE TITLE
Export to JOSM doesn't work with Chrome/Chromium

### ISSUE THREAD

**Issue by ricloy** [osm-fr/osmose-frontend#361]
When using Chrome/Chromium browser, clicking on Export → JOSM, apparently does nothing; the following error message is shown in the browser console:

`GET https://localhost:8111/load_object?objects= net::ERR_SSL_PROTOCOL_ERROR`

If I run JOSM in a terminal, I can see what happens from the JOSM point of view:

```
2022-03-09 20:59:29.873 INFORMAZIONI: RemoteControl received: �O��Mn^�"������(��^�-��;J�vj�7� ���������2Y�ner����e}O�}S:��� ���+�/�,�0��������/5���
                 	localhost�
2022-03-09 20:59:29.874 INFORMAZIONI: RemoteControl received: GET /load_object?objects= HTTP/1.1
2022-03-09 20:59:29.874 AVVERTENZA: 'load_object' remote control request must have 'objects' parameter
2022-03-09 20:59:29.887 INFORMAZIONI: RemoteControl received: �r�._0n�������������,G%VS�y�*A ��v)rL�<��K��;��3��SE�I�m���� ���+�/�,�0��������/5�**
                                                                                                                                                  	localhost�`
```
Everything works fine (although a couple of warnings) when clicking "josm", "fix-josm" or "josm-zone" in any issue's popup. 

Firefox doesn't seem to be affected by the problem.

Chromium version: 99.0.4844.51

Might be duplicate of #314 or #358.

Kind regards,
Marco.

**Comment by frodrigo** [comment]
[](https://matrix.to/#/!fdQuIPZzzMzrCiZONx:matrix.org/$poqLKdJxZiXreODgrDIX6RyAPKxrpIAUwk_r97y9MNo?via=matrix.org&via=tchncs.de&via=converser.eu)https://josm.openstreetmap.de/changeset/15469/josm

**Comment by ricloy** [comment]
Someone suggested in a public chat to mitigate the problem by using the JOSM plugin [openqa](https://gitlab.com/gokaart/JOSM_OpenQA) (which loads Osmose/KeepRight issues on JOSM without using the browser).

**Comment by frodrigo** [comment]
A change have been made. Please can you recheck if it is better for you.

**Comment by ricloy** [comment]
I checked with Chromium 99.0.4844.51 and Firefox 98.0 and Export to JOSM seems to work pretty fine for both browsers.

Thanks!
