### ISSUE TITLE
Name corruption

### ISSUE THREAD

**Issue by SomeoneElseOSM** [osm-fr/osmose-frontend#363]
OSM's Data Working Group have received a complaint that Osmose can corrupt names.  See the changes to https://www.openstreetmap.org/way/420016000/history - the change in https://www.openstreetmap.org/changeset/117701158 was allegedly "Fixed with Osmose".

Is it possible that Osmose could decide that a name is "wrong" and change it, or is the mapper saying  "Fixed with Osmose" when they themselves have chosen the invalid names?

**Comment by frodrigo** [comment]
Osmose only raise possible issues, or suggest changes based on rules.

All OSM changes are manually validated / done by a contributor.

Osmose it self does not make any changes to OSM.

**Comment by frodrigo** [comment]
This changeset is big. There is not hard limitation of contributors to do this #164.
On Osmose there is already a welcome panel, with short warning about that.

Osmose may suggest bad changes. We can improve Osmose if you spot more some precisely and report on Osmose backend https://github.com/osm-fr/osmose-backend/issues

**Comment by SomeoneElseOSM** [comment]
> All OSM changes are manually validated / done by a contributor.

Whilst that should be the case, as https://github.com/osm-fr/osmose-frontend/issues/164 and https://github.com/osm-fr/osmose-frontend/issues/362 note it clearly isn't the case right now - contributors ignore on-screen advice.

> Osmose only raise possible issues, or suggest changes based on rules.

> Osmose may suggest bad changes. We can improve Osmose if you spot more some precisely and report on Osmose backend https://github.com/osm-fr/osmose-backend/issues

Can you move this issue there?  I've no idea exactly why the change to https://www.openstreetmap.org/way/420016000/history was made, but clearly the change was invalid.

**Comment by SomeoneElseOSM** [comment]
This can be closed now https://github.com/osm-fr/osmose-backend/issues/1415 is open.
