### ISSUE TITLE
Issue URL gives a 404 error (insee.fr)

### ISSUE THREAD

**Issue by adrienandrem** [osm-fr/osmose-frontend#369]
Item 8310, class 4502001  
example: https://osmose.openstreetmap.fr/en/issue/899938de-1484-44ba-0836-ca18da953454

Issue URL leads to _not found_ page:  
https://avis-situation-sirene.insee.fr/ListeSiretToEtab.action?form.nic=00010&form.siren=789545985  
whereas https://sirene.fr/sirene/public/recherche gives a result.

**Comment by frodrigo** [comment]
Duplicate #335
