### ISSUE TITLE
errors disappear

### ISSUE THREAD

**Issue by Haikuch** [osm-fr/osmose-frontend#37]
depending on the chosen map section, error signs seem to disappear. While moving the map, they are sometimes shown, sometimes not. See pictures (taken by mknight)

https://www.picflash.org/picture.php?key=ZAOAXU&action=show
vs
https://www.picflash.org/picture.php?key=V3Y3DB&action=show

http://forum.openstreetmap.org/viewtopic.php?pid=606379#p606379

**Comment by mmd-osm** [comment]
Uploading images, Github does not need external image provider.

![a68tcxpuixsvgsw](https://cloud.githubusercontent.com/assets/5842757/18077241/9b5ce6be-6e84-11e6-964a-d585ee42b135.png)
![k5zhlds9ln0plr0](https://cloud.githubusercontent.com/assets/5842757/18077242/9b800aa4-6e84-11e6-8291-410de647a657.png)

**Comment by jocelynj** [comment]
Yes, that's quite strange. If I understand the problem correctly, it is linked to the permalink stuff. It includes lat and lon, and these values are not reset when moving the map.

**Comment by mmd-osm** [comment]
It's more an issue of markers disappearing when moving the map. Take a look at the 4 markers above "K 38" between the two water areas. When moving the map around, the suddenly disappear, although the area is in the bbox all the time.

**Comment by jocelynj** [comment]
I just did a quick trial: if I remove  `lat=51.80606&lon=10.33244&` from the map url you gave earlier, then moving the map shows the correct markers.
I'm wondering if the fix coule be to remove lat and lon to the `map/markers?` url used to fetch markers from map.

**Comment by mmd-osm** [comment]
Yes, leaving out lat/lon seems to make a difference. I wonder if there's maybe some bad interaction between several events, i.e. URL updating / caching markers / loading markers / removing markers somehow interferes which each other.
