### ISSUE TITLE
Export metrics for dashboards

### ISSUE THREAD

**Issue by brawer** [osm-fr/osmose-frontend#381]
To build dashboards for mapathons, could Osmose export a CSV file with the following columns?

* `date`: the date in ISO 8601 format, eg. `2022-07-21`;
* `issue_class`: the numeric id for the [Osmose issue class](https://wiki.openstreetmap.org/wiki/Osmose/issues), eg. 31601 for “bad lanes value”;
* `region`: the Osmose-specific string id for the country and region, one of the values in [api/0.3/countries](http://osmose.openstreetmap.fr/api/0.3/countries), eg. `france_lorraine_moselle`;
* `num_unresolved_issues`: how many Osmose issues have still been open/unresolved at the end of `date` in `issue_class` within the geographic `region`, eg. `789` if there were 789 lanes with a bad lanes value at the end of July 21, 2022, in Lorraine-Moselle;
* `num_fixed_issues`: how many Osmose issues have been marked as fixed during this date in this issue class and geographic region;
* `num_false_positives`: how many Osmose issues have been marked as false positives during this date in this issue class and geographic region.

In a second step, could the Osmose frontend display a dashboard that graphically plots how the number of open and fixed issues evolved over time, restricted by issue class and region? Such a dashboard would be hugely motivating when organizing a mapathon event because volunteers can see how the collective effort has improved things day by day.

**Comment by frodrigo** [comment]
The stats are not part of the API yet. But it is planned to move from the web frontend to the API (help welcome).

Meanwhile you can have this data from this URL
http://osmose.openstreetmap.fr/en/issues/open.json?country=france_aquitaine_gironde&item=xxxx&limit=0
Since it is not in the API it will subject to change in the future.

**Comment by lbuchli** [comment]
Hm ok, then it probably doesn't fit, because statistics about users is the primary goal of Project of the Month. Thanks for your feedback!

**Comment by frodrigo** [comment]
cc @PanierAvide FYI
