### ISSUE TITLE
Class filtering doesn't work

### ISSUE THREAD

**Issue by Ptigrouick** [osm-fr/osmose-frontend#384]
On item=7170 when I try to filter with class=1, I get all items and not only those of class=1. I think class filtering don't work anymore.

**Comment by frodrigo** [comment]
Do you have more details. Because it looks fine to me
https://osmose.openstreetmap.fr/en/issues/open?item=7170&class=1

**Comment by Ptigrouick** [comment]
https://osmose.openstreetmap.fr/en/map/#item=7170&class=1&zoom=11&lat=43.6168&lon=3.6982&level=1%2C2%2C3
![2022-07-21_22-55_osmose](https://user-images.githubusercontent.com/9768270/180313722-b912a5a4-1d7d-4785-9452-12f784c0eb79.png)
I get all classes of item 7170, not only "route potentiellement manquante à proximité (BD Topo IGN)". I did a big clean of class=1 on my area and 3 days ago I saw all items with the same URL.

**Comment by frodrigo** [comment]
On the switch to FastAPI the parameter was renamed `classs` (3 x `s`). While the API use `class`.

So the current `class` parameter is not read.

I do not see how to fix it cleanly. I ask for help https://github.com/tiangolo/fastapi/discussions/5184

**Comment by frodrigo** [comment]
Fixed.
