### ISSUE TITLE
Level filtering doesn't work

### ISSUE THREAD

**Issue by praszuk** [osm-fr/osmose-frontend#387]
`https://osmose.openstreetmap.fr/en/byuser/<username>?level=1`
It returns all the issues assigned to a specific user with ignoring level parameter.

Probably related to these issues:
https://github.com/osm-fr/osmose-frontend/issues/383
https://github.com/osm-fr/osmose-frontend/issues/384

**Comment by frodrigo** [comment]
Fixed, but due to the volume of code touched may come with new issues.
