### ISSUE TITLE
Clicking elems href on /byuser (User Statistics) site returns 404

### ISSUE THREAD

**Issue by praszuk** [osm-fr/osmose-frontend#389]
Before it was redirecting to the OSM object.
![User Statistics](https://user-images.githubusercontent.com/23036224/183390130-8ea6d977-e0c6-4095-bbd4-ea2b462d3979.jpg)
![Error after clicked](https://user-images.githubusercontent.com/23036224/183390168-96e43d7b-fe98-44d9-b1ee-dcc725d46b7c.jpg)

**Comment by frodrigo** [comment]
Thank for report. Fixed.
