### ISSUE TITLE
building overlaps are not listed in "own" errors  

### ISSUE THREAD

**Issue by dex2000** [osm-fr/osmose-frontend#39]
errors with id=0 are not shown in the byuser-errorlist

Example: http://osmose.openstreetmap.fr/de/byuser/?username=silverlion 
vs: http://osmose.openstreetmap.fr/de/map/#zoom=18&lat=48.409727&lon=13.317142&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFT&item=&level=1%2C2%2C3&tags=&fixable=

In additional of that, the selection for id/item 0 doesnt work too:
http://osmose.openstreetmap.fr/de/byuser/?username=silverlion&item=0

**Comment by jocelynj** [comment]
That's strange - I'm taking a look.

**Comment by jocelynj** [comment]
Ok, it is because backend is sending the minimal information on ways that trigger this error - only way_id, and no tags or username.

@frodrigo: do you see any issue in modifying the use of self.way to self.way_full to fetch all information ? It could have some impact on performance.

**Comment by frodrigo** [comment]
It's because it's the most numerous issue, more than 1 400 000 of the total 25 742 168. So it's can be done but there will be come with more data to upload and store on the frontend part.

**Comment by dex2000** [comment]
frodrigo: i dont understand the second part of your post, please explain "So it's can be done but there will be come with more data to upload and store on the frontend part." in french, i will let translate that for me.

**Comment by dex2000** [comment]
if i understand you correctly: its possible and should be implemented but it can made problems in the future?

**Comment by jocelynj** [comment]
What @frodrigo means is that if we add more information on these errors from item 0, then it will take more space in the frontend database, and it will take a longer time to run this analyser.

Not having username on errors with item 0 is a compromise between speed/space and usefulness.
