### ISSUE TITLE
Listing Osmose issues as HTML doesn't work

### ISSUE THREAD

**Issue by praszuk** [osm-fr/osmose-frontend#391]
It returns "TypeError: Failed to fetch". I thought it was caused by [this error](https://github.com/osm-fr/osmose-backend/issues/1510), but probably it is not.

To reproduce:
`Osmose map -> Export -> Html list`

Example URLs which don't work:
[All issues categories/items in region](https://osmose.openstreetmap.fr/pl/issues/open?country=poland_mazowieckie&item=xxxx)
[Specific item in region](https://osmose.openstreetmap.fr/pl/issues/open?country=poland_mazowieckie&item=1070)
[Specific item with specified class](https://osmose.openstreetmap.fr/pl/issues/open?source=8484&item=1210&class=1)

**Comment by frodrigo** [comment]
A bad configuration was deploy on server. Fixed.

**Comment by frodrigo** [comment]
A bad configuration was deploy on server. Fixed.
