### ISSUE TITLE
RSS feed is returning invalid JSON

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-frontend#392]
My RSS feed has this entry (added today) which returns "detail: not found" message.  Earlier entries in the RSS feed (from July 16) are working.

http://osmose.openstreetmap.fr/en-CA/map/#zoom=18&item=0000%252C1010%252C1040%252C1050%252C1060%252C1080%252C1090%252C1100%252C1110%252C1140%252C1150%252C1160%252C1170%252C1180%252C1190%252C1200%252C1210%252C1220%252C1221%252C1230%252C1240%252C1250%252C1270%252C1280%252C2xxx%252C3xxx%252C4020%252C4040%252C4060%252C4061%252C4070%252C4080%252C4090%252C4100%252C4110%252C4130%252C6xxx%252C7010%252C7011%252C7012%252C7020%252C7050%252C7051%252C7060%252C7070%252C7080%252C7090%252C7100%252C7110%252C7120%252C7130%252C7140%252C7150%252C7160%252C7170%252C7190%252C7220%252C7240%252C8010%252C8011%252C8012%252C8020%252C8021%252C8022%252C8025%252C8026%252C8030%252C8031%252C8032%252C8040%252C8041%252C8042%252C8050%252C8051%252C8060%252C8070%252C8080%252C8110%252C8120%252C8121%252C8122%252C8130%252C8131%252C8132%252C8140%252C8150%252C8160%252C8161%252C8162%252C8170%252C8180%252C8190%252C8191%252C8192%252C8200%252C8201%252C8202%252C8210%252C8211%252C8221%252C8230%252C8240%252C8250%252C8260%252C8270%252C8280%252C8281%252C8290%252C8320%252C8330%252C8331%252C8340%252C8341%252C8350%252C8351%252C9000%252C9001%252C9002%252C9003%252C9004%252C9005%252C9006%252C9007%252C9009%252C9010%252C9014%252C9015%252C9016%252C9100&level=1%252C2&tags=&fixable=&limit=500&bbox=-75.77596664428712%252C45.31232182518018%252C-75.52310943603517%252C45.41447897237767&zoom=16&lat=45.3478751&lon=-75.7731949&level=2&tags=&fixable=&issue_uuid=5392d1d1-a079-de36-ca4e-8bcf07f14a3a

**Comment by matthewdarwin** [comment]
That's what my RSS reader shows.
Here is old one working:
![image](https://user-images.githubusercontent.com/26171839/184030311-37471e94-25f5-4472-9452-a05870b3d486.png)

http://osmose.openstreetmap.fr/en/map/#zoom=18&item=0000%2C1010%2C1040%2C1050%2C1060%2C1080%2C1090%2C1100%2C1110%2C1140%2C1150%2C1160%2C1170%2C1180%2C1190%2C1200%2C1210%2C1220%2C1221%2C1230%2C1240%2C1250%2C1270%2C1280%2C2xxx%2C3xxx%2C4020%2C4040%2C4060%2C4061%2C4070%2C4080%2C4090%2C4100%2C4110%2C4130%2C6xxx%2C7010%2C7011%2C7012%2C7020%2C7050%2C7051%2C7060%2C7070%2C7080%2C7090%2C7100%2C7110%2C7120%2C7130%2C7140%2C7150%2C7160%2C7170%2C7190%2C7220%2C7240%2C8010%2C8011%2C8012%2C8020%2C8021%2C8022%2C8025%2C8026%2C8030%2C8031%2C8032%2C8040%2C8041%2C8042%2C8050%2C8051%2C8060%2C8070%2C8080%2C8110%2C8120%2C8121%2C8122%2C8130%2C8131%2C8132%2C8140%2C8150%2C8160%2C8161%2C8162%2C8170%2C8180%2C8190%2C8191%2C8192%2C8200%2C8201%2C8202%2C8210%2C8211%2C8221%2C8230%2C8240%2C8250%2C8260%2C8270%2C8280%2C8281%2C8290%2C8320%2C8330%2C8331%2C8340%2C8341%2C8350%2C8351%2C9000%2C9001%2C9002%2C9003%2C9004%2C9005%2C9006%2C9007%2C9009%2C9010%2C9014%2C9015%2C9016%2C9100&level=1%2C2&tags=&fixable=&limit=500&bbox=-75.77596664428712%2C45.31232182518018%2C-75.52310943603517%2C45.41447897237767&zoom=16&lat=45.3478751&lon=-75.7731949&level=2&tags=&fixable=&issue_uuid=739ccefb-f4ff-45e9-9e3a-aef1e0b1fd19

**Comment by frodrigo** [comment]
Ok, I see 2 issues
- not supported langue
- double URL encoding

**Comment by matthewdarwin** [comment]
This is the RSS feed: 
http://osmose.openstreetmap.fr/en/issues/open.rss?zoom=18&item=0000%2C1010%2C1040%2C1050%2C1060%2C1080%2C1090%2C1100%2C1110%2C1140%2C1150%2C1160%2C1170%2C1180%2C1190%2C1200%2C1210%2C1220%2C1221%2C1230%2C1240%2C1250%2C1270%2C1280%2C2xxx%2C3xxx%2C4020%2C4040%2C4060%2C4061%2C4070%2C4080%2C4090%2C4100%2C4110%2C4130%2C6xxx%2C7010%2C7011%2C7012%2C7020%2C7050%2C7051%2C7060%2C7070%2C7080%2C7090%2C7100%2C7110%2C7120%2C7130%2C7140%2C7150%2C7160%2C7170%2C7190%2C7220%2C7240%2C8010%2C8011%2C8012%2C8020%2C8021%2C8022%2C8025%2C8026%2C8030%2C8031%2C8032%2C8040%2C8041%2C8042%2C8050%2C8051%2C8060%2C8070%2C8080%2C8110%2C8120%2C8121%2C8122%2C8130%2C8131%2C8132%2C8140%2C8150%2C8160%2C8161%2C8162%2C8170%2C8180%2C8190%2C8191%2C8192%2C8200%2C8201%2C8202%2C8210%2C8211%2C8221%2C8230%2C8240%2C8250%2C8260%2C8270%2C8280%2C8281%2C8290%2C8320%2C8330%2C8331%2C8340%2C8341%2C8350%2C8351%2C9000%2C9001%2C9002%2C9003%2C9004%2C9005%2C9006%2C9007%2C9009%2C9010%2C9014%2C9015%2C9016%2C9100&level=1%2C2&tags=&fixable=&limit=500&bbox=-75.77596664428712%2C45.31232182518018%2C-75.52310943603517%2C45.41447897237767

**Comment by frodrigo** [comment]
Fixing langue negotiation.

URL encoding was fine.
