### ISSUE TITLE
Country filtering: empty dropdown list

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-frontend#393]
Hello,

See the title: to select a country is impossible, as the list is empty :(

Thx for the fix (if a fix is relevant).

**Comment by frodrigo** [comment]
Issue on main map.

**Comment by frodrigo** [comment]
Fixed.
Curiously it was never implement nor reported before.

**Comment by deuzeffe** [comment]
> Fixed.

Yesss! Thx. At last, I can use department AND issue filtering \o/

> Curiously it was never [...] reported before.

I've already reported. On the IRC chan. Hum. My bad
