### ISSUE TITLE
Item 1080 (orphan nodes): osm id isn't shown

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-frontend#394]
Hello,

For item 1080, the popup on the map doesn't show the osm id of the nodes. And JOSM export returns logically an error (Les clés suivantes sont obligatoires mais n'ont pas été fournies: objects).

But on the issue page (for ex. https://osmose.openstreetmap.fr/fr/issues/open?country=france_limousin_haute_vienne&item=1080), the JOSM link runs fine and orphan nodes are properly downloaded.

Is it magic or I don't understand how to use this issue ?

Thx for the answer, whatever it is.

**Comment by frodrigo** [comment]
It works as intended.
As it is a group of nodes, the id are not listed.
From the popup you can use josm-zone directly.
