### ISSUE TITLE
HTTPS support of API

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-frontend#396]
There is a redirection from HTTPS to HTTP.

Stop this redirection. Even better make it reverse.

**Comment by frodrigo** [comment]
@jocelynj to you change something on this ?

**Comment by frodrigo** [comment]
It is from ols URL when redirected to the API

https://osmose.openstreetmap.fr/en/issues/open.csv?zoom=17&item=xxxx&level=1&limit=500&bbox=38.7652587890625%2C8.95019282586578%2C38.7762451171875%2C8.966471298599469
08-15 20:29:36.232 15982 16003 E osmose  : exception: CLEARTEXT communication to osmose.openstreetmap.fr not permitted by network security policy

**Comment by jocelynj** [comment]
Fixed by always redirecting to https, even if the original url was in http
```
        RewriteRule "^/[a-z_]+/issues/open.(rss|kml|gpx|csv|geojson)" "https://%{SERVER_NAME}/api/0.3/issues.$1" [R,L]
```
