### ISSUE TITLE
Haute-Vienne, France: nothing to integrate? 

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-frontend#397]
Hello,

In Haute-Vienne no markers for integration objects (items 8010 -> 8530) but shops and milestones.

Is it normal?

**Comment by frodrigo** [comment]
Not sure what is wong for you ?
http://osmose.openstreetmap.fr/fr/map/#item=8350&zoom=12&lat=45.8192&lon=1.2639

**Comment by deuzeffe** [comment]
Perhaps the query by department is not relevant?
https://osmose.openstreetmap.fr/fr/issues/open?country=france_limousin_haute_vienne&item=8350&level=1,2,3&limit=500

**Comment by frodrigo** [comment]
> Perhaps the query by department is not relevant? https://osmose.openstreetmap.fr/fr/issues/open?country=france_limousin_haute_vienne&item=8350&level=1,2,3&limit=500

Yes. It is not a geographical filter. But an analyzer filter. And this analyzers at run at France level.
I understand the trouble it causes, but cannot do better for now.

**Comment by deuzeffe** [comment]
Ok. Thx for your answer. We'll wait for better days...
