### ISSUE TITLE
improve error dialog?

### ISSUE THREAD

**Issue by bagage** [osm-fr/osmose-frontend#40]
Bonjour,
Actuellement, la popup qui s'ouvre lorsqu'on clique sur une erreur est la suivante : 
![capture d ecran de 2016-09-25 21-10-00](https://cloud.githubusercontent.com/assets/1451988/18817589/8190445c-8364-11e6-8fd2-57b4367d9c44.png)
En tant qu'utilisateur j'y trouve plusieurs soucis #: 
* [ ] 1. Comme on ne peut ouvrir qu'une seule popup à la fois, on peut grossir celle-ci sans vraiment de soucis (voir points suivants)
* [x] 2. les liens `osm-show` `osm-edit` et `josm zone` ne sont pas très amicaux : pourraient-ils être changés par des phrases explicites "Se rendre à cette position sur openstreetmap.org", "Éditer cette zone avec l'éditeur en ligne d'openstreetmap.org" et "Télécharger la zone dans JOSM" par exemple ?
* [x] 3. Idem pour "changer le status" : les liens `corrigé` et `faux positif` ne pourraient-ils pas être des boutons plutôt avec une icône sympathique ;-)?
* [x] 4. La date du signalement devrait se retrouver en bas de la popup à mon avis 
* [x] 4.bis (et revoir la phrase "signalement signalé" qui fait doublon)
* [x] 5. Les icônes "?" et surtout "E" ne sont pas très visibles, c'est dommage, et n'ont pas de texte associé (on hover ou autre)
* [ ] 6. Au lieu de charger le wiki lorsqu'on sélectionne "?", ne pourrait-on pas faire afficher un sous-morceau de la popup qui décrit l'erreur, histoire de ne pas quitter la page ?
* [x] 7. Je suppose que l'icône "E" affiche des informations de debug ? Possibilité de la renommer en "D[ebug]" plutôt si c'est le cas ? Histoire que l'utilisateur "normal" n'y fasse pas pas attention.
* [ ] 8. Concernant la résolution de l'erreur et plus particulièrement ici pour le cas de l'intégration d'une BAL non intégréé, il n'y a pas de guidage précis (peut-être est-ce l'[erreur 8025](http://wiki.openstreetmap.org/wiki/FR:Osmose/issues#8025) qui n'est pas bien renseigner sur le wiki ?). Mais j'aurai aimé savoir quel(s) clé(s)/valeur(s) Osmose s'attend à trouver afin de ne plus considérer une erreur. Je pense que cela est générique est s'applique pour toutes les erreurs, avoir la liste clés/valeurs attendues ne me paraît pas inutile.

Je sais que cela fait beaucoup de critiques, mais ne vous méprennez-pas : osmose fait déjà un super boulot et je vous encourage à continuer sur cette lancée :smile: !

**Comment by jocelynj** [comment]
Merci pour les remarques.

1. Je préférerais garder les popups de taille assez petite, pour pouvoir regarder rapidement d'autres erreurs voisines, mais c'est vrai qu'on pourrait afficher les infos plus clairement. Est-ce qu'afficher des infos dans un coin de la carte serait mieux ? (par exemple, en bas du menu).

2. On peut rajouter un hover ici, ça suffirait ?

3. Les boutons ne sont plus à la mode en html :) Par contre, on doit pouvoir mettre des icônes si tu penses que ça serait plus lisible.

4. Yep, phrase à revoir - avant, c'est "Erreur signalé le:", ce qui ne faisait pas doublon.

5. Exact, un hover me parait pertinent.

6. Hum, c'est une bonne idée.

7. Yep, c'est une info de debug, surtout pour obtenir le numéro de l'erreur concernée par cette popup. E, c'était pour "erreur", mais ce n'est plus pertinent. D me parait bien.

8. On pourrait mettre un lien direct vers le code source de l'analyse qui a généré l'erreur: ça serait surtout utile si on arrive à documenter toutes les analyses dans un format clair pour les utilisateurs.

**Comment by frodrigo** [comment]
8. Can be extracted automatically from merge the analysers, it's a config. For the others, maybe set it in the code and then generate and translate this data.

**Comment by bagage** [comment]
1. There is no need for a centered popup. Instead osmose could behavi like umap by using a lateral sidebar.
2. A hover would be better but not sufficient enough I am afraid.
3. Icons are fine yes.
8. If it's possible it would be great; users' can help improve documentation when needed?

I'll try to add some UX design.

**Comment by frodrigo** [comment]
"signalement signalé" fixed

**Comment by bagage** [comment]
Here is a basic mockup of what it could look like (much of it is borrowed from UMap btw!).
![mockup](https://cloud.githubusercontent.com/assets/1451988/20629851/ec20ea26-b32d-11e6-9117-eeb348ebba01.png)

What do you think of it?

**Comment by jocelynj** [comment]
It is better than I thought it would be :)

I'm wondering if we can really add that many explanation on all error types. Do you think all necessary information is on the wiki ?

**Comment by bagage** [comment]
I doubt there are but that's a part of the plan: we should add them! It is definitely worth it in my opinion. There are "only" 144 entries to make - even at start it can be very basics information which will be modified by contributors with the time ;).
Do you think it's doable? I actually also wanted to revamp the left panel, but also the markers… then I thought: I would actually use UMap for everything:

- the "edit this marker" (the only available mockup yet) is a copy of the UMap edit panel
- markers could have a specific icon (eg. mailbox for mailbox issues, wheelchair for accessibility issues, etc.) using Maki icons, Font awesome or something else... So that it's easier to spot issues directly on the map.
- issues by category and severity could be put in UMap layers.

Basically it looks like UMap has everything needed (with a few tweaks ;)) for this and it would reduce the cost of maintaining osmose frontend. But for now it's only an idea, I'm not aware of the feasibility…

**Comment by frodrigo** [comment]
![image](https://user-images.githubusercontent.com/1785486/44100304-18d5d414-9fe5-11e8-8218-29dd54dddf01.png)

**Comment by frodrigo** [comment]
1. Do not forget the mobile devices
6. Reported to #101
8. Reported to #102

**Comment by Marc-marc-marc** [comment]
corrigé -> icone vert : c'est mieux !
? -> i : c'est mieux
mais l'icone rouge, il y a un risque de confusion entre annuler et faux-positif

**Comment by frodrigo** [comment]
Oui, c'est de l'unicode. Il n'y a rien à traduire.
Chez moi celui avec le rond ne s'affiche pas. J'ai donc pris l'autre.

J'ai ajouté une demande de confirmation pour le faux positif.
