### ISSUE TITLE
False positive orphan nodes?

### ISSUE THREAD

**Issue by emersonveenstra** [osm-fr/osmose-frontend#400]
When I view https://osmose.openstreetmap.fr/en/issue/3651ce08-df93-eeb0-1697-7d677c11dac7 using either iD or JOSM, i don't see any nodes that are orphaned. Is there any other way to get a list of nodes that caused the issue?

**Comment by frodrigo** [comment]
Last report is from 2 days ago. It may be already solved. Wait for next update. In principle every 24h.

**Comment by emersonveenstra** [comment]
It's gone now 👍
