### ISSUE TITLE
Internal server errors for benches with direction

### ISSUE THREAD

**Issue by Nadyita** [osm-fr/osmose-frontend#401]
I'm getting an internal server error every time I'm trying to open the details for 3 issues ([like this one](https://osmose.openstreetmap.fr/api/0.3/issue/df6dca43-27b1-df97-aab3-f2d11f4eb2b7?langs=auto))

All 3 issues seem to be related to benches with the following attributes:

```
amenity=bench
backrest=yes
direction=125
material=wood
seats=4
```
I don't see any issues with these attributes, but something is definitely causing the API to return a 500, and you might want to investigate what. These are the only benches with a direction-attribute in the area, so I'm positively sure it's related to this.

**Comment by frodrigo** [comment]
This issue is related to the new version of analyser result upload API, currently under beta test.

In fact it corrupt a database jsonb field by double encoding it.

**Comment by frodrigo** [comment]
Fixing the corrupted data and the code.

```sql
UPDATE
    markers
SET
    elems = (SELECT array_agg((elem #>> '{}')::jsonb) FROM unnest(elems) AS elem)
WHERE
    elems IS NOT NULL AND
    jsonb_typeof(elems[1]) = 'string'
;
UPDATE
    markers
SET
    fixes = (SELECT array_agg((elem #>> '{}')::jsonb) FROM unnest(fixes) AS elem)
WHERE
    fixes IS NOT NULL AND
    jsonb_typeof(fixes[1]) = 'string'
;
```
