### ISSUE TITLE
Something wrong?

### ISSUE THREAD

**Issue by Neuwessi11** [osm-fr/osmose-frontend#403]
Yesterday I could not reach osmose.openstreetmap.fr due to maintenace.
Today I can reach it, but only a little part of the formerly detected mistakes are detected now. E.g. in a whole city of 250.000 inhabitants is now detected not only one mistake of "überlappende Gebäude" (sorry, I don't know the English word), where two days ago were dozens of them.
And general the map is now much "less colorful" than before.

**Comment by frodrigo** [comment]
> Something wrong?

In short yes.

We have many troubles running Osmose from multiple causes.


Do you have an Osmose link ?

**Comment by Neuwessi11** [comment]
https://osmose.openstreetmap.fr/de/map/#zoom=12&lat=51.1752&lon=6.4646&item=1xxx%2C2xxx%2C3xxx%2C4xxx%2C5xxx%2C8xxx%2C9xxx&level=1

Good luck with fixing the bugs!

**Comment by Neuwessi11** [comment]
I am sorry, the settings changed.
This time including "überlappende Gebäude":
https://osmose.openstreetmap.fr/de/map/#zoom=12&lat=51.1752&lon=6.4646&item=1xxx%2C2xxx%2C3xxx%2C4xxx%2C5xxx%2C8xxx%2C9xxx&level=1

**Comment by frodrigo** [comment]
Ensure the value of the severity filter, top left.

https://osmose.openstreetmap.fr/en/map/#zoom=11&lat=51.2863&lon=6.7922&item=0000&level=1%2C2%2C3

Still a lot.
But with good trending ;-)
https://osmose.openstreetmap.fr/en/issues/graph.png?item=0&country=germany_%2a

**Comment by Neuwessi11** [comment]
In your link the overlapping buildings appear, and when clicking other categories everything keeps fine. But when I click the "all"-button, most elements disappear.

But at least for know I know a way to handle it: by clicking every category single.
