### ISSUE TITLE
Downloading to .kml the gibberish of a specific user does not work.

### ISSUE THREAD

**Issue by wzbartczak** [osm-fr/osmose-frontend#411]

**Comment by frodrigo** [comment]
Please, can you provide a link or more details?

**Comment by wzbartczak** [comment]
` http://osmose.openstreetmap.fr/en/api/0.3/issues.kml?level=3&usename=Cristoffs `
This link does not work. Every attempt fails.

**Comment by frodrigo** [comment]
Just tested it now and it works.
