### ISSUE TITLE
Downloading of user errors in the form of geojson

### ISSUE THREAD

**Issue by wzbartczak** [osm-fr/osmose-frontend#412]

**Comment by frodrigo** [comment]
Please, can you provide a link or more details?

**Comment by wzbartczak** [comment]
It is possible to download usage error data via the website with its statistics, e.g.  [My link](https://osmose.openstreetmap.fr/en/byuser/Cristoffs?level=3)

It would be great if in addition to being able to download in .kml and .gpx it was possible to download .geojson (Currently downloading in .kml and .gpx does not work unfortunately - reported)

**Comment by frodrigo** [comment]
In fact there is no link with geojson. But it works already. Just use with .geojson.

But yes, I would be nice to have all this links listed.

**Comment by frodrigo** [comment]
Done
