### ISSUE TITLE
Use color in heatmap

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-frontend#42]
Use circle or other thing to combine colors

**Comment by dex2000** [comment]
is that the new "color" of the heatmap? imho not so good, found the old colors better: https://www.picflash.org/viewer.php?img=qkz7w22vocksoyo.png

**Comment by frodrigo** [comment]
Please, can you explain more ?

**Comment by frodrigo** [comment]
![default](https://cloud.githubusercontent.com/assets/1785486/19365988/9b9a5b3c-9195-11e6-9233-f62917fcc84a.png)

**Comment by dex2000** [comment]
Ah i see.
was wondering about only grey dots in overlapping buildings. (grey is not very good to see color-differences)
But its ok, no problem.
