### ISSUE TITLE
Broken urls in popover

### ISSUE THREAD

**Issue by elcaptain** [osm-fr/osmose-frontend#424]
When you click on an issue on the map some links in the popover are broken. Specifically the one to edit the feature in the iD editor.
The linked url is (e.g.): https://osmose.openstreetmap.fr/en/map/edit?editor=id&node=330838332
And it should be: https://openstreetmap.org/edit?editor=id&node=330838332
![Screenshot 2022-11-18 at 11 29 42](https://user-images.githubusercontent.com/15268562/202681414-913a7064-ea49-46ae-9bbe-6106674102d5.png)

**Comment by frodrigo** [comment]
I do not see this issue.

https://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=39.478666&lon=-0.363101&item=xxxx&level=1%2C2%2C3&tags=&issue_uuid=6d016a1c-f0b3-b555-261d-1aca617d41ff

Please, can you recheck.

**Comment by elcaptain** [comment]
Hey @frodrigo, now it seemed to work correctly for me too. No clue what happened there.
