### ISSUE TITLE
http://osmose.openstreetmap.fr/en/login gives Error: 500 Internal Server Error

### ISSUE THREAD

**Issue by MarcBessieres** [osm-fr/osmose-frontend#43]
Hello,

When, on the map, clicking on login button on the top bar I get a 500 Internal Server Error.

Clicking on login means going to the web page:
http://osmose.openstreetmap.fr/en/login

And here is the output on the screen.

> Error: 500 Internal Server Error
> 
> Sorry, the requested URL 'http://osmose.openstreetmap.fr/en/login' caused an error:
> 
> Internal Server Error
>

**Comment by MarcBessieres** [comment]
As an additional comment, I started using it after the presentation of Frederic at SOTM, and it worked fine the last time for me on the 4th, and the 5th or the 6th it started failing

**Comment by frodrigo** [comment]
openstreetmap.org send back some different errors while trying to do OAuth

> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"\\n   "http://www.w3.org/TR/html4/loose.dtd">\\n<html>\\n<body>\\n  <img src="/assets/osm_logo.png" style="float:left; margin:10px">\\n  <div style="float:left;">\\n    <h1>Application error</h1>\\n    <p>The OpenStreetMap server encountered an unexpected condition that prevented it from fulfilling the request (HTTP 500)</p>\\n    <p>Feel free to <a href="http://wiki.openstreetmap.org/wiki/Contact" title="Various contact channels explained">contact</a> the OpenStreetMap community if your problem persists. Make a note of the exact URL / post data of your request.</p>\\n    <p>This may be a problem in our Ruby On Rails code. 500 occurs with exceptions thrown outside of an action (like in Dispatcher setups or broken Ruby code)</p>\\n  </div>\\n</body>\\n</html>\\n

or

> 104, 'Connection reset by peer'

**Comment by MarcBessieres** [comment]
Hi, it works now. I presume you change the code to accept both. Thank you for the quick fix!

**Comment by frodrigo** [comment]
No, we just waited osm.org send back again valid answers.

**Comment by MarcBessieres** [comment]
Ok, then I was too quick in reporting it even if I waited for several days. Thank you anyway!
