### ISSUE TITLE
graph bug with option start_date 

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-frontend#430]
there is a bug with start_date 
http://osmose.openstreetmap.fr/en/issues/graph.png?country=spain_andalucia_malaga&item=1230&class=3,4&start_date=2022-07
=> bug
http://osmose.openstreetmap.fr/en/issues/graph.png?country=spain_andalucia_malaga&item=1230&class=3,4
=> ok

**Comment by frodrigo** [comment]
Fixed
