### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by Dimitar5555** [osm-fr/osmose-frontend#432]
Currently when trying to open http://osmose.openstreetmap.fr the browser is loading/trying to connect for a very long time before giving up. It would be very useful if there was an automatic redirect to the https version of the requested page.

**Comment by Dimitar5555** [comment]
Yes, I still have it. I'm using Firefox 107.0 (latest release version as of now) if that makes any difference.

**Comment by jocelynj** [comment]
That's very strange. Do you see the same issue when opening https://osmose.openstreetmap.fr, or http://beta.osmose.openstreetmap.fr?

**Comment by frodrigo** [comment]
Do you konw if your are using ipv6 or not?

**Comment by Dimitar5555** [comment]
> That's very strange. Do you see the same issue when opening https://osmose.openstreetmap.fr, or http://beta.osmose.openstreetmap.fr?

Only when opening the second link, the first one works as expected (since it's https).

> Do you konw if your are using ipv6 or not?

afaik IPv6's Windows service is disable on my machine and it shouldn't be able to access IPv6 addresses. https://ipv6-test.com shows IPv6 connectivity as "Not supported".

**Comment by frodrigo** [comment]
> Resolving map (map)... failed: No address associated with hostname.

It do it with wget but not with firefox.

It is rather an issue for https://github.com/osm-fr/infrastructure/issues than directly osmose ?

**Comment by frodrigo** [comment]
Now we redirect to HTTPS
