### ISSUE TITLE
Edit panel under info panel

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-frontend#437]
Not sure what should happen but I see no result or error.

![Peek 2022-12-26 17-35](https://user-images.githubusercontent.com/899988/209568168-6a2c279f-c1e8-4e49-b6e2-e6ea3c856ff8.gif)

**Comment by matkoniecz** [comment]
I disabled adblock

Query being made is `https://osmose.openstreetmap.fr/api/0.3/issue/1d171859-2363-b986-ebf8-36bf37e22173/fresh_elems`

**Comment by turbotimon** [comment]
This tricked me too.... You must first close the pop-up window "Redirected value for Wikidata tag" to your right (X).

**Comment by turbotimon** [comment]
To the developers: Maybe it is possible to close the "Info" pop-up when you press "edit", "fix-edit" or any other action that show an other pop-up underneath?

I'm supposing me and Mateusz are not the only ones falling for that..

**Comment by frodrigo** [comment]
Ok got it. Edit panel is under info panel.

**Comment by frodrigo** [comment]
Fixed. Close doc before showing editor.
