### ISSUE TITLE
Mobile doesn't allow for closing of the "welcome" dialog

### ISSUE THREAD

**Issue by thibaultmol** [osm-fr/osmose-frontend#440]
When you open osmose on a mobile browser (both chrome and firefox seem affected), the dialog on the right that says "welcome to osmose-qa" doesn't want to go away if you press the X icon.

https://www.whatsmybrowser.org/b/ZPGVZ

https://www.whatsmybrowser.org/b/7IF3N

https://user-images.githubusercontent.com/1010226/209922740-41f5a87b-4e03-444e-b5b3-144daee90214.mp4

**Comment by frodrigo** [comment]
Thank you for quick report.
This bug was introduced by deploy last night.
Now fixed.

**Comment by thibaultmol** [comment]
Thx for the quick fix!
