### ISSUE TITLE
`openstreetmap wikidata quality checker` can not upload

### ISSUE THREAD

**Issue by turbotimon** [osm-fr/osmose-frontend#441]
hi @frodrigo 

since some days, the `openstreetmap wikidata quality checker` is not able to upload his reports. Response is **403**
last successful upload was on 2022-12-23

reproduce with:
```
curl --request POST --form analyser='Wikidata' --form country='andorra' --form code='<secret>' --form content=@report_AD_andorra.xml https://osmose.openstreetmap.fr/control/send-update
```

**Comment by frodrigo** [comment]
It should have be removed.

@jocelynj are you able to regenerate the sources into the frontend?

**Comment by frodrigo** [comment]
Sorry. But the main server cached and we cannot change the configuration for now.

**Comment by turbotimon** [comment]
Ok, please let me know when it works again. when do you expect it to work again?

**Comment by frodrigo** [comment]
@turbotimon have you been able to try an upload ? There is still nothing on Osmose-QA side.

**Comment by turbotimon** [comment]
@frodrigo sorry i did have seen your comment. yes it works again, thanks!

**two questions:**
1. i can not find our analyzer in the [update_matrix](https://osmose.openstreetmap.fr/de/control/update_matrix). Whats our name there and are we the only analyzer with this name?
2. Can we sent [Antartica](https://github.com/osm-fr/osmose-backend/blob/fe158f2c45eac2d0a210cd22a8d0f0d9af68087e/osmose_config.py#L821)? It has no boundary id in the osmose_config.py? But we would use [2186646](https://www.openstreetmap.org/relation/2186646#map=2/-77.7/0.0)

**Comment by frodrigo** [comment]
As the matrix is a big page there is a cache. I can see it now.

**Comment by frodrigo** [comment]
> 

> 2\. Can we sent [Antartica](https://github.com/osm-fr/osmose-backend/blob/fe158f2c45eac2d0a210cd22a8d0f0d9af68087e/osmose_config.py#L821)? It has no boundary id in the osmose_config.py, but we would use [2186646](https://www.openstreetmap.org/relation/2186646#map=2/-77.7/0.0)

Add added it.
