### ISSUE TITLE
Clicking 'open' issues from false positive list doesn't load open issues

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-frontend#443]
1. Start on https://osmose.openstreetmap.fr/nl/issues/false-positive?item=1170
2. Click "open" to show the open issues in the left top corner. You'll be send to https://osmose.openstreetmap.fr/nl/issues/open?item=1170&status=false
3. The issues shown are still the false positives.
4. Removing `&status=false` gets you to the open issue list

**Comment by frodrigo** [comment]
Fixed.
