### ISSUE TITLE
"Hide from map" not working

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-frontend#450]
1. Open any balloon on the map
2. Press "hide from map" in the sidebar on the right

Expected:
- Item is deselected in the list on the left, balloons corresponding to this item are hidden

Observed
- Nothing changes

(Browser: Chrome)

**Comment by JackNUMBER** [comment]
Tested on Firefox, there is the same error.
No error in console.

It seems there is a prevent on the button click, [here](https://github.com/osm-fr/osmose-frontend/blob/de10fbb27b0458176389febbc037c69f927b56b6/web/src/pages/map/doc.vue#L75).

**Comment by frodrigo** [comment]
Fixed
