### ISSUE TITLE
Require confirm before marking as false positive

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-frontend#457]
When marking an issue from the map as a false positive, you'll have to confirm this every time via a pop-up.
https://github.com/osm-fr/osmose-frontend/blob/00f26b2d6d265519ca7abb01aa1fe7b80b515cf2/web/src/pages/map/popup.vue#L398-L402

However, in the issue list [(example)](https://osmose.openstreetmap.fr/nl/issues/open?item=1210&class=3) or user detection list [(example)](https://osmose.openstreetmap.fr/nl/byuser/Famlam) there's no confirmation after clicking the ✘-button, allowing some people to mark the entire list as false positives within minutes (some analysers have over 20 false positives marked within 1 minute, all by one user). This is very likely by users who don't understand that the false positive marking is not to hide it from their own list, but to hide it for everyone.

Proposed solution: make the user confirm that (s)he really wants to mark the issue as false positive and has at least read the implications, by requiring the same confirmation popup to be "OK"ed in the issue list, similar to marking an issue as false positive in the map view

**Comment by frodrigo** [comment]
Good point.

I also suggest replace the confirm dialog text from 

> Report the issue as improper, if it is not an issue according to you. The issue will not be displayed to anyone anymore.

to

> Report the issue as improper.
>
>Warning, the issue will also no more displayed to other contributor. If you unsure, let this Osmose issue open.
>
>Use only if the Osmose report issue is in fact not an OSM data issue in this special case.
>
>If Osmose report lots of think like this one and you are disagree with this report, please fill an Github bug issue and let us try to fix this.

**Comment by Famlam** [comment]
I agree, that is much better. Just fixed some wording here:
> Report the issue as improper.
Only use this if the issue reported by Osmose is in fact not an issue in the OSM data.
Warning: the issue will also no longer be displayed to other contributors. If you are unsure, let this Osmose issue open.
If Osmose reports lots of issues similar to this one and you disagree with this, please fill a Github issue and let us try to fix it.

**Comment by frodrigo** [comment]
> I agree, that is much better. Just fixed some wording here:

Thank you.

Done and deployed.

> p.s. I haven't been able to build the frontend yet (Windows innocent) and I'm not familiar with vue, so I'll have to leave it to you to implement this see_no_evil.

The JS part is the easier part to run. It can be done without docker.
