### ISSUE TITLE
building-overlaps/gaps in baden-württemberg

### ISSUE THREAD

**Issue by dex2000** [osm-fr/osmose-frontend#46]
See: http://osmose.openstreetmap.fr/de/map/#zoom=18&lat=48.056568&lon=9.87806&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT&item=0&level=1%2C2%2C3&tags=&fixable=
was fixed (on OSM) on 14.07. error is shown there.
have set status=fixed on an (same false) error in the near, its gone correctly. (maybe have to wait 3 days and its come back?)

That problem isnt the only in Ba-Wü, there are a lot of others, like:
http://osmose.openstreetmap.fr/de/map/#zoom=18&lat=48.097857&lon=9.545563&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT&item=0&level=1%2C2%2C3&tags=&fixable= or similar

Problem is, the errors only going gone if set manually to fixed.

There is a thread in the forum about that (german): 
https://forum.openstreetmap.org/viewtopic.php?id=56089

**Comment by dex2000** [comment]
http://osmose.openstreetmap.fr/de/map/#zoom=18&lat=48.071465&lon=10.127007&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT&item=0&level=1%2C2%2C3&tags=&fixable=

The 2 errors on the bottom (housenumber 31) was set manually to fixed, but there are back again.

Looks like you have not actually extract of Baden-württemberg?

**Comment by jocelynj** [comment]
You're right that these errors should no longer be reported by Osmose - at least according to what I saw on JOSM. And the used extract contains the latest version of both ways. I will take a copy of the extracts for further analyses.

**Comment by dex2000** [comment]
thx

**Comment by dex2000** [comment]
any news?

**Comment by frodrigo** [comment]
Issues are gone for real or not ?

According to the graph I will say there are still here, but I don't see they on the map.
http://osmose.openstreetmap.fr/de/errors/graph.png?country=germany_baden_wuerttemberg&item=0

**Comment by dex2000** [comment]
Jep, looks like its gone.
