### ISSUE TITLE
Offer statistics per administrative boundary

### ISSUE THREAD

**Issue by PanierAvide** [osm-fr/osmose-frontend#463]
As now, Osmose offer statistics for a given item through `/issues/graph.json` endpoint. It can be filtered either by _country_ (regional extract) or a bounding box. Would it be complex / feasible to add filtering based on administrative boundary ?

- With different levels (based on OSM `admin_level` ?)
- For every administrative entity (using its official ref or OSM ref ?)

**Comment by frodrigo** [comment]
No. It would suppose to store each issues from each delay update in the history.

We "just" store the count for each (item,class,country). And we already have 2Go of that.
