### ISSUE TITLE
Osmose exports seem incomplete

### ISSUE THREAD

**Issue by severinmenard** [osm-fr/osmose-frontend#464]
I exported in geojson format an area from Eastern DRC, regarding only the disconnected highways, but many issues seem missing, as shown below:

![Screenshot1752](https://github.com/osm-fr/osmose-frontend/assets/1291055/6617187b-318f-49ea-b33d-407854a3d4c6)

It may be related to some restrictions I can see in the filters (eg https://osmose.openstreetmap.fr/fr/issues/open?item=1210)  where, even you input a bbox, only a portion of the issues are displayed and you need to click on the hyper link at the bottom many times to supposedly get everything when you see the number of issues is not increasing anymore (but no message is provided)

![Screenshot1753](https://github.com/osm-fr/osmose-frontend/assets/1291055/3c68f8ef-f313-4132-9409-8f49fe6559e6)

**Comment by frodrigo** [comment]
The output by API have a number limit. You can add a `limit` param

https://osmose.openstreetmap.fr/api/docs

But event with limit, there is a max.

**Comment by severinmenard** [comment]
@frodrigo the API doc says the limit is 500, but I managed to get a few thousand by clicking on "Afficher plus de signalements". What could be improved IMO is that you this way you do not know the total number of issues in your bbox nor the number you have got after each click (eg XXX/YYY)
