### ISSUE TITLE
KML download produces invalid KML

### ISSUE THREAD

**Issue by voomdoon** [osm-fr/osmose-frontend#466]
If i download my KML, i get

```
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
...
  </Document>
  <Placemark>
...
  </Placemark>
</kml>
```

but `Placemark`must be inside of `Document`

e.g. https://osmose.openstreetmap.fr/en/api/0.3/issues.kml?&username=voomdoon

**Comment by frodrigo** [comment]
Fixed. The KML is now more valid, but not completely valid.
