### ISSUE TITLE
byuser_count 404 : url changed and/or missing redirect ?

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-frontend#471]
https://hdyc.neis-one.org/ got an 404 when trying to request byuser_count
`95.216.34.51 - - \[13/Jul/2023:23:22:55 +0000\] "GET /en/byuser_count/azamnawa HTTP/1.0" 404 173 "https://resultmaps.neis-one.org" "Java/11.0.18"`

**Comment by frodrigo** [comment]
The API is at `https://osmose.openstreetmap.fr/api/0.3/user_count/azamnawa`

**Comment by frodrigo** [comment]
All users in one call should be better for hdyc.neis-one.org

**Comment by Marc-marc-marc** [comment]
> The API is at `https://osmose.openstreetmap.fr/api/0.3/user_count/azamnawa`

I have send the info by email to Pascal Neis

> All users in one call should be better for hdyc.neis-one.org

does this exist or need to be coded ?

**Comment by pa5cal** [comment]
Thanks for noticing, @Marc-marc-marc !
I just switched to the mentioned API 0.3: `https://osmose.openstreetmap.fr/api/0.3/user_count/username`

**Comment by Marc-marc-marc** [comment]
thanks, stats are well updated
