### ISSUE TITLE
Item 3040 - incorrect tag: Concerns `crossing=informal`

### ISSUE THREAD

**Issue by mcliquid** [osm-fr/osmose-frontend#473]
The item 3040 returns errors for "Concerns tag: `crossing=informal`".
Link: https://osmose.openstreetmap.fr/en/issues/open?item=3040

This value is set to junctions for the StreetComplete query "Specify if there are junctions at intersections of paths and roads".
The OpenStreetMap Wiki entry for this can be found here: https://wiki.openstreetmap.org/wiki/Tag:crossing=informal

Is this really a error?

**Comment by Famlam** [comment]
This has been merged into backend, so it is solved, but I can't close frontend issues. Can someone close this issue?
