### ISSUE TITLE
False positive list doesn't load

### ISSUE THREAD

**Issue by emersonveenstra** [osm-fr/osmose-frontend#474]
Clicking the link from https://osmose.openstreetmap.fr/en/ takes me to https://osmose.openstreetmap.fr/en/issues/false-positive which displays a 404 page
![Screenshot 2023-08-28 at 4 47 39 PM](https://github.com/osm-fr/osmose-frontend/assets/5402360/af0e8f50-d2ed-4161-bdbc-70cf714d8f2d)

**Comment by frodrigo** [comment]
If you are here https://osmose.openstreetmap.fr/en/ your are lost ! There no intended content on this page.

Page to be removed.

**Comment by emersonveenstra** [comment]
What's the correct URL to view the false positive list?

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/issues/false-positive?item=8270

**Comment by Famlam** [comment]
It also seems that this list now continuously yields a `Error: 500 Internal Server Error` instead of loading the list.
This happens for several days already

**Comment by frodrigo** [comment]
Fixed. Sorry for long delay.

**Comment by Famlam** [comment]
No worries, thanks for fixing :)
