### ISSUE TITLE
links to "ref:FR:FINESS" and "ref:FR:SIRET" do not arrive on the site

### ISSUE THREAD

**Issue by lenny31** [osm-fr/osmose-frontend#475]
I have an error on an object with the keys "ref:FR:FINESS" and "ref:FR:SIRET" https://osmose.openstreetmap.fr/fr/issue/fce3a9c5-aad2-3581-dc95-510ebf5b1f4f ; when I am on the map if I clic on the values the page is not ok :
- ref:FR:FINESS = [310780150](http://finess.sante.gouv.fr/fininter/jsp/actionDetailEtablissement.do?noFiness=310780150)
I have `This site is inaccessible`
- ref:FR:SIRET = [41818521100020](https://avis-situation-sirene.insee.fr/ListeSiretToEtab.action?form.nic=00020&form.siren=418185211) I have the good site sirene but not the "Médipôle Garonne" page

**Comment by Linkid** [comment]
An issue already exists for the SIRET ref: #335.

**Comment by frodrigo** [comment]
Switch to new tag2link
https://github.com/JOSM/tag2link
