### ISSUE TITLE
Including city names in the "Subtitle" column

### ISSUE THREAD

**Issue by polish96** [osm-fr/osmose-frontend#480]
I am writing to ask a suggestion for improving the error reporting system on the OpenStreetMap Osmose platform. I have encountered a problem while using the following link:

https://osmose.openstreetmap.fr/en/issues/open?country=poland_slaskie&item=2060&level=2&source=&class=19&tags=&username=&bbox=&fixable=

In the table provided on the webpage, coordinates of the problematic locations are listed along with the specified street name that is missing in the vicinity of the given element. I have noticed that sometimes the map lags, fails to display all elements, or takes a long time to load. Considering these issues, I would like to propose an enhancement for your consideration.

I believe that incorporating the names of cities into the existing "Subtitle" column would significantly improve the usability of the platform. This additional information would simplify the process of grouping errors by town or city and street name. As coordinates alone do not always provide precise information about the area in question, including the name of the city would enhance the user experience and make error resolution more efficient.

I genuinely believe that this change could have a positive impact on the user interface and overall user satisfaction.

Thank you for considering my suggestion.

**Comment by frodrigo** [comment]
You can filter by "country", list here http://osmose.openstreetmap.fr/api/0.3/countries

But you can also use the `bbox` param to limit the area.
