### ISSUE TITLE
pins are often misplaced

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-frontend#483]
![screen02](https://github.com/osm-fr/osmose-frontend/assets/899988/347f4bb9-9eaa-49c5-b809-a2241846c903)
![screen01](https://github.com/osm-fr/osmose-frontend/assets/899988/ece36cdc-999b-4974-b3f8-c7e19c16cae7)

https://osmose.openstreetmap.fr/en/map/#zoom=18&lat=50.061295&lon=19.939702&item=xxxx&level=1%2C2%2C3&issue_uuid=5c68d8d4-be3b-52fb-f291-27a3f365561b

triggered by 

> It's the red pin with the black square on your screenshot. On the Osmose website, pins are often at the wrong location, no idea when and why.

at https://github.com/Helium314/SCEE/issues/504#issuecomment-1872950553

**Comment by frodrigo** [comment]
Duplicate #366
