### ISSUE TITLE
Fixes are not saved immediately

### ISSUE THREAD

**Issue by HubMiner** [osm-fr/osmose-frontend#487]
I made a few separate fixes a few minutes ago, and saved multiple times - I should endo up with multiple changesets.
JOSM "close open change sets" says: There are no open change sets.
My user history shows that the last fix was 6 hours ago.

**Comment by frodrigo** [comment]
Change are send directly to the API. I'm afraid the the changes are lost.
Should be an issue with the recent switch to OAuth2.

**Comment by frodrigo** [comment]
I have not yet identifier what append. The OSM.org API may accept or not the changeset upload process. When nothing is uploaded, it create anyway empty changeset. It may not be linked to the OAuth2 changes.

Bad think is that the Osmose code fails silently on this. I will try first to fix this point.

**Comment by frodrigo** [comment]
> Bad think is that the Osmose code fails silently on this. I will try first to fix this point.

Not it shows an error when it fails.

**Comment by frodrigo** [comment]
I found the source of the issue. An UTF-8 encoding issue.
I have deployed a fix.

I don't know why and when it could have been broken. But is was not directly linked to OAuth2. May come from dependencies update when switching to OAuth2.
