### ISSUE TITLE
Upload fails

### ISSUE THREAD

**Issue by severinmenard** [osm-fr/osmose-frontend#488]
Hello, I was teaching Osmose yesterday in an online session in English and unfortunately the service was slow. But I also faced several upload failures when I tried to use the internal tagging editor and upload the changes. It never worked. You can see this on the recording of the session: https://youtu.be/VLJRSMHz5XA?si=edievt8SbUChNaI3&t=1834

**Comment by frodrigo** [comment]
See #487
Do you note any error messages ?

**Comment by severinmenard** [comment]
Nothing showed up on my screen, you can see in the video that I figured out the upload had failed when I went to my OSM history and saw that there was no new changeset.

**Comment by frodrigo** [comment]
Fixed. See #487 for details.
