### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by HubMiner** [osm-fr/osmose-frontend#489]
This might be related to https://github.com/osm-fr/osmose-frontend/issues/487

- Starting with a fresh guest profile in Chrome
- open https://osmose.openstreetmap.fr/en/map/
- click login
- https://www.openstreetmap.org/login?referer= ...
- enter credentials
- page opens: https://osmose.openstreetmap.fr/en/map/
- However, it still shows "Login" instead of username.
- Clicking Login again - page reloads, nothing happens.

There is no option to logout, except by deleting cookies.

**Comment by frodrigo** [comment]
I can confirm the issue. That a client side cache issue.

I look to me that is not related to #487

cc @jocelynj

**Comment by jocelynj** [comment]
With @frodrigo, we did some changes the cache configuration on pages to login/logout and to report if connected. Can you check if it works better for you now?

**Comment by HubMiner** [comment]
@jocelynj,  @frodrigo,
It works now!  Many thanks!

**Comment by frodrigo** [comment]
Thank all.
