### ISSUE TITLE
error list displays coordinates link broken. missing 'en'

### ISSUE THREAD

**Issue by harry-wood** [osm-fr/osmose-frontend#49]
On error list displays like this one: http://osmose.openstreetmap.fr/en/byuser/Harry%20Wood?level=1 there's a column with coordinates which are linked with URL such as this one: http://osmose.openstreetmap.fr/map/#&item=1050&zoom=17&lat=-0.9260361&lon=100.3613016&level=1
...which doesn't work. It redirects to not include coordinates.
It looks like that should be this with an 'en' in there:
http://osmose.openstreetmap.fr/en/map/#&item=1050&zoom=17&lat=-0.9260361&lon=100.3613016&level=1

**Comment by frodrigo** [comment]
I think you encountered an other issue.

The lat & lon param are used to set map location and are present.

Moreover the link you provide works for me.

**Comment by harry-wood** [comment]
Ah hang on....  [the URL](http://osmose.openstreetmap.fr/map/#&item=1050&zoom=17&lat=-0.9260361&lon=100.3613016&level=1) works if I log out. So this is only an issue while logged in. Maybe only if logged in as an english person

**Comment by frodrigo** [comment]
Hum, may be an issue with the space in your nick name.

**Comment by frodrigo** [comment]
Please, can you check now? It could be fixed by last changes.

**Comment by harry-wood** [comment]
Yes I think it's **fixed**. Thanks!

**Comment by frodrigo** [comment]
Glad to know. Thank you.
