### ISSUE TITLE
Login to OSM is no longer possible.

### ISSUE THREAD

**Issue by gitcookie-1** [osm-fr/osmose-frontend#496]
Login to OSM is no longer possible.

**Comment by jocelynj** [comment]
We have just migrated to a new server, mostly because the old one was saturated.

It should work better, except for login that doesn't work anymore, that we need to investigate.

**Comment by jocelynj** [comment]
It should work now: I had made a mistake on the configuration in `modules/utils.py`, forgotting to add `https://`
