### ISSUE TITLE
Stuck at lowest zoom level

### ISSUE THREAD

**Issue by opk12** [osm-fr/osmose-frontend#499]
1. Open Osmose.
2. Give a strong touchpad scroll to zoom out as much as possible.
3. The URL becomes https://osmose.openstreetmap.fr/en/map/#loc=0.1/0/-98.5
4. You cannot zoom in again, by scrolling, or by clicking the `+` button at the top right.
5. To fix, reopen Osmose and zoom in before it finishes loading.

**Comment by frodrigo** [comment]
I am no able to reproduce this issue.
Do you have any error in the console ?

**Comment by frodrigo** [comment]
The fronted was update. Please can you check you still have the issue, or not ?

**Comment by opk12** [comment]
Sorry for the late reply. I have not seen it happen again. I will close the issue.
