### ISSUE TITLE
change overlay and bg doesnt work anymore

### ISSUE THREAD

**Issue by dex2000** [osm-fr/osmose-frontend#50]
If i want to change map-background i get error in Firefox-console:

    TypeError: a is undefined
    http://osmose.openstreetmap.fr/de/map/leaflet.select-layers.min.js
    Line 6

If i want to change overlay i.e to heatmap i get:

    TypeError: this._layers[c.layerId] is undefined
    http://osmose.openstreetmap.fr/de/map/leaflet.select-layers.min.js
    Line 6

**Comment by frodrigo** [comment]
Just try the `F5` key. Maybe linked issue with leafleat update weeks ago.

**Comment by dex2000** [comment]
It's not a caching-problem.

It doesnt work on small monitors/ viewports (with the small menu)

on greater monitors with the great menu it works without the error above.

Small Monitor:
![small](https://cloud.githubusercontent.com/assets/5686458/21750050/b2dbcf66-d5aa-11e6-9fc3-0d5c52e13b68.png)
Great Monitor
![great](https://cloud.githubusercontent.com/assets/5686458/21750051/b2df5730-d5aa-11e6-9554-de30534b90df.png)

**Comment by frodrigo** [comment]
I got the point.

In fact I see the Leaflet plugin https://github.com/vogdb/SelectLayersControl is not compatible with Leaflet 1.0. But It's no more required. Leaflet 1.0 already deals right with the layer menu on small screen.
