### ISSUE TITLE
Hide button non-functional

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-frontend#506]
1. Go to https://osmose.openstreetmap.fr/nl/map/#zoom=8&lat=52.241&lon=5.504&item=xxxx&level=1%2C2%2C3&loc=16/51.958375/5.896081&issue_uuid=8065e3c2-db00-656f-0f60-1c4d26d7ffda
2. Click the hide button to hide all issues of a certain type: 
![image](https://github.com/osm-fr/osmose-frontend/assets/1315520/1bccb876-72ed-4ad1-9953-6bc8517259ad)
3. Nothing happens

**Comment by frodrigo** [comment]
Fixed
