### ISSUE TITLE
Wide popups usually half off-screen

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-frontend#507]
For very wide popups, you (usually) don't see the full popup. 
When opening it it's dependent on the map, but after dragging the map a little bit, it is always half.

Example [here](https://osmose.openstreetmap.fr/nl/map/#zoom=8&lat=52.241&lon=5.504&item=xxxx&level=1&loc=16/51.84818/5.858642&issue_uuid=742511d2-5433-117b-40fc-fc7f4bcdb263)

Either it looks like this:
![image](https://github.com/osm-fr/osmose-frontend/assets/1315520/98db248b-7492-4b0d-bad9-e1c1c0f0ed3c)
Or like this:
![image](https://github.com/osm-fr/osmose-frontend/assets/1315520/384dbfae-3523-4d2b-b660-5f686fb17f14)

Occasionally I get it like this, which isn't perfect either, but at least 90% is visible:
![image](https://github.com/osm-fr/osmose-frontend/assets/1315520/21a48143-9c8b-4eef-8f4a-0d2c57b534f1)

Ideally, it would limit the popup width to for instance 50% of the "map region" width, either by word-wrapping the text if it's too long, or having a horizontal scroll bar for the tags.

**Comment by frodrigo** [comment]
Max width is already implemented, but does not work.

https://github.com/osm-fr/osmose-frontend/blob/master/web/static/map/Osmose.Marker.ts#L24

**Comment by Famlam** [comment]
Just a stupid suggestion, but in the defaults I see a unit is specified (https://github.com/maplibre/maplibre-gl-js/blob/0b4688b5c34bfa4dab4e956d0e67d2703bd1ec95/src/ui/popup.ts#L20) while in Osmose it isn't. 

If I use `200` for css, nothing happens: 
![image](https://github.com/osm-fr/osmose-frontend/assets/1315520/6bf9b0be-7036-4908-b7e8-74b937757389)


If I use `200px` for css, I get 
![image](https://github.com/osm-fr/osmose-frontend/assets/1315520/c67c4294-51ea-44e6-a09c-54a23cba1631)

**Comment by frodrigo** [comment]
Good catch! I miss this point when I look at this before.

**Comment by frodrigo** [comment]
Fixed. Thank you.
