### ISSUE TITLE
old data in thüringen

### ISSUE THREAD

**Issue by dex2000** [osm-fr/osmose-frontend#51]
see: http://osmose.openstreetmap.fr/de/map/#country=germany_thueringen&item=0&zoom=13&lat=50.5852415&lon=10.4123717&level=3

All problems there was fixed on January 23, see https://www.openstreetmap.org/way/233100684 for example

**Comment by jocelynj** [comment]
That's very strange, as I can confirm that this way is not present in the original extract used for running the analyses.

I've asked the responsible for the server for german_thuerigen to check if there is anything incorrect.

**Comment by tkas** [comment]
Hello,

germany_thueringen seemed fine, but for sure I removed all related files. Will check the situation on Monday after fresh run os osmose is done.

Thanks for the check.

**Comment by dex2000** [comment]
The errors are gone, thx.

**Comment by dex2000** [comment]
found a new error: 
http://osmose.openstreetmap.fr/de/map/#country=germany_thueringen&item=0&zoom=13&lat=50.8633986&lon=12.0726411&level=3

**Comment by tkas** [comment]
Checked the state - just to be sure - the last modification of this is 2017-02-27, right? Thueringen last run 2017-03-09 19:00:01 with data from 2017-03-08T21\:43\:02Z.  Will check the data on server and on geofabric to see if there is a difference.

Bye

**Comment by dex2000** [comment]
mod is from Feb 26, yes

**Comment by tkas** [comment]
Just checked germany_thueringen.osm.pbf from 2017-03-09 19:00 and it contains changeset 46419968.

**Comment by tkas** [comment]
Seems to be gone, but I don't know what causes it to go away. Close, if there is a problem again, pls let us know.

**Comment by dex2000** [comment]
will reopen, if it comes back :)
(maybe someone have set it to fixed manually)
