### ISSUE TITLE
Strageness with a first edit

### ISSUE THREAD

**Issue by HubMiner** [osm-fr/osmose-frontend#512]
After I start fresh, make a change for a single object and click Done:

1) Unexpected pop up message:
You have made a large number changes with the tags editor. Think about saving your changes. You can save multiple times while keeping the same changeset.
- This is a consistent behavior in the last few days.

2) That pin does not dissapear from the map.  
- If I try to edit the same pin again, it will result in server error 500 (messing up a bigger changeset).
- Sometimes it is possible to mark the pin as green/corrected (just to get it off the map).

**Comment by frodrigo** [comment]
> Unexpected pop up message: You have made a large number changes with the tags editor. Think about saving your changes. You can save multiple times while keeping the same changeset.

Was set to 1 change as debug. I fixed it to raise the alert at 30 changes.

> That pin does not dissapear from the map.

I do not got this issue.

> error 500

Yes, That linked to the fact that the pin is no more available... but you still get it on the screen.

**Comment by HubMiner** [comment]
I tested again (a few days later) - the issue is no longer there.
Thanks!
