### ISSUE TITLE
Link to Sandre database not working

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/osmose-frontend#517]
How reproduce:
- Enable item integration 8830
- Search wastewater_plant can be integrated into OSM
- Open link in the pop-up to open Sandre website with id -> website not working

Example:
- http://www.services.eaufrance.fr/donnees/service/028846802594 -> The new link is https://id.eaufrance.fr/SysTraitementEauxUsees/028846802594

**Comment by frodrigo** [comment]
You can configure links on this project
https://github.com/JOSM/tag2link

**Comment by Marc-marc-marc** [comment]
maj wikidata effectuée https://www.wikidata.org/w/index.php?title=Property%3AP1717&diff=2249126844&oldid=2201390868
aucune idée des caches en oeuvre
