### ISSUE TITLE
Integrate Keepright, OSMI and MapDust?

### ISSUE THREAD

**Issue by grischard** [osm-fr/osmose-frontend#52]
This is just an idea, and I'm not sure if it's worth the trouble...

Currently, Osmose doesn't try to reproduce the checks that other QA tools do. Many of these tools have an export function:

* [OSMI has WFS access](https://wiki.openstreetmap.org/wiki/OSM_Inspector/WxS)
* KeepRight has `export.php?format=geojson`
* MapDust has GeoRSS

Would it be possible to integrate these as category trees in the Osmose frontend?

**Comment by frodrigo** [comment]
About KeepRight is no more right. As I do an experiment about remake analyses in Osmose.
https://github.com/keepright/keepright/tree/master/checks
All analyses of KeepRight up to 0180 was already is Osmose or I add it to Osmose in the last 3 month.
(cc @mueschel)

**Comment by frodrigo** [comment]
We previously have osm bug item, but we remove it when it was closed.
We can imagine support MapDust.

**Comment by grischard** [comment]
@frodrigo should I open a separate issue for OSMI?

**Comment by frodrigo** [comment]
For now, I don't want to integrate OSMI.
