### ISSUE TITLE
website url are link to google cache url ???

### ISSUE THREAD

**Issue by vinber** [osm-fr/osmose-frontend#520]
![image](https://github.com/user-attachments/assets/467fc768-662a-405c-9c6c-00ea16e9a8cb)

url are

 `https://webcache.googleusercontent.com/search?q=cache:https://www.hipopo.fr/boutique-bordelaise/
`

i would to go to website

**Comment by frodrigo** [comment]
Link use the JOSM tag2link project. Itself using wikidata to store links template.

It should be "fixed" into wikidata, or reported to tag2link project for exception.

https://github.com/JOSM/tag2link
