### ISSUE TITLE
Negros Island in Philippines Not Seen in OSMOSE Dashboard

### ISSUE THREAD

**Issue by adiatmad** [osm-fr/osmose-frontend#521]
1. **Overview of the Issue:**
   - I can not see the data quality issue in Negros Island especially around Mount Kanlaon, located in the [Western Visayas region of the Philippines](https://osmose.openstreetmap.fr/en/map/#country=philippines_western_visayas&item=xxxx&loc=9/10.5768/123.1932&level=1), in the OSMOSE dashboard.

2. **Significance of Negros Island:**
   - There is currently an eruption at [Mount Kanlaon](https://www.aljazeera.com/news/2024/12/9/evacuations-under-way-in-philippines-as-mt-kanlaon-volcano-erupts), a volcano on Negros Island, and some of the local communities are utilizing OpenStreetMap data to respond to the situation and plan mitigation efforts.

3. **Proposed Action:**
   - I kindly request that the OSMOSE team investigate this issue and consider adding Negros Island to the OSMOSE dashboard.

   Thank you for your attention to this matter. I look forward to your response and any updates.
   
![image](https://github.com/user-attachments/assets/6c81b27e-c1ae-45b9-81c9-1769ca8c9bdb)

**Comment by jocelynj** [comment]
We must have forgotten some sub-divisions when we split Philippines a few year ago :( 

Can you check the list at https://download.openstreetmap.fr/extracts/asia/philippines/ and tell us which sub-divisions are missing?

**Comment by jocelynj** [comment]
The number of regions in Philippines have changed. We only have 16 in osmose and extracts, but there are now 18 of them. It looks like they have changed in the past years: https://en.wikipedia.org/wiki/Regions_of_the_Philippines#Timeline.

I will update the region lists in download.openstreetmap.fr

**Comment by jocelynj** [comment]
Negros Island is being added by https://github.com/osm-fr/osmose-backend/pull/2409

**Comment by jocelynj** [comment]
We now have issues in Negros Island: https://osmose.openstreetmap.fr/en/map/#country=philippines_negros_island_region&item=xxxx&loc=9/10.0964/122.9676&level=1
