### ISSUE TITLE
See count of all items (for one territory)?

### ISSUE THREAD

**Issue by grischard** [osm-fr/osmose-frontend#53]
Is it possible to see the count of all error items, maybe for a territory?

Like http://osmose.openstreetmap.fr/fr/errors/?country=luxembourg&item=1120 but for all items.

I would love to be able to [make a treemap](https://bl.ocks.org/mbostock/4063582) of all errors.

**Comment by grischard** [comment]
Ahh, I just discovered http://osmose.openstreetmap.fr/fr/errors/?country=luxembourg&item=*

Would it be possible to have an "All items" option in the items menu?

**Comment by frodrigo** [comment]
humm, just let the item selector empty.

**Comment by grischard** [comment]
Hmm, but http://osmose.openstreetmap.fr/fr/errors/?country=luxembourg&item= or http://osmose.openstreetmap.fr/fr/errors/?country=luxembourg&item or http://osmose.openstreetmap.fr/fr/errors/?country=luxembourg don't give me a list of all items.

**Comment by frodrigo** [comment]
Yes, you have to set item=xxxx explicitely. It's to avoid load on server side, not all countries have the same size ;-).

**Comment by frodrigo** [comment]
It would be nice to stack the issues  item/color/levle/whatever on the graphe
http://osmose.openstreetmap.fr/fr/errors/graph.png?country=luxembourg&item=xxxx&level=1
