### ISSUE TITLE
popup orientation problem and display 'nothing' shows quite a lot. 

### ISSUE THREAD

**Issue by DaveF63** [osm-fr/osmose-frontend#54]
Hi
Could the popup be orientated to the icon so it always displays fully on screen? See KeepRight as an example.
I suspect that might have been discussed in #40, but I'm afraid my French is poor.

------

When the overall 'nothing' is selected, multiple icons display. I'd expect the map to be empty. Is there an intentional reason for this?

**Comment by frodrigo** [comment]
In fact it's an issue with leaflet used to display the map. KeepRight use OpenLayer and it have this feature.
There an old plugin for this but it's look ugly: http://erictheise.com/rrose/

I just see there is a new one:
https://github.com/yafred/leaflet-responsive-popup
let give a try.

**Comment by DaveF63** [comment]
Great. The demo performs as I hoped. It this could be easily integrated it would certainly improve the user experience.

**Comment by DaveF63** [comment]
Unfortunately it ignores the left hand menu
![image](https://user-images.githubusercontent.com/9528328/32519439-ab82e224-c404-11e7-80b9-50962819d7f9.png)

**Comment by frodrigo** [comment]
It was already the case.

**Comment by DaveF63** [comment]
True. Is there a way to fix it?

**Comment by frodrigo** [comment]
leaflet-active-area and leaflet-responsive-popup doesn't seem to play together.
