### ISSUE TITLE
Could you help help to introduce how to deploy frontend on my own CentOS?

### ISSUE THREAD

**Issue by gzqlovemxq** [osm-fr/osmose-frontend#55]

**Comment by frodrigo** [comment]
Do you flow the instruction of https://github.com/osm-fr/osmose-frontend/blob/master/README.md ?
Do you have a more specific problem ?

**Comment by gzqlovemxq** [comment]
I follow the instruction, but I deploy the frontend on my CentOS OS.
And the following issues happened when I access my frontend:

`[Tue May 16 23:08:49.734387 2017] [:error] [pid 23546] [remote 172.18.157.33:46865] mod_wsgi (pid=23546): Exception occurred processing WSGI script '/var/www/test/osmose.wsgi'.
[Tue May 16 23:08:49.734406 2017] [:error] [pid 23546] [remote 172.18.157.33:46865] Traceback (most recent call last):
[Tue May 16 23:08:49.734419 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]   File "/usr/lib/python2.7/site-packages/beaker/middleware.py", line 152, in __call__
[Tue May 16 23:08:49.734433 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]     return self.wrap_app(environ, session_start_response)
[Tue May 16 23:08:49.734440 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]   File "/var/www/test/bottle.py", line 979, in __call__
[Tue May 16 23:08:49.734450 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]     return self.wsgi(environ, start_response)
[Tue May 16 23:08:49.734457 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]   File "/var/www/test/bottle.py", line 974, in wsgi
[Tue May 16 23:08:49.734465 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]     start_response('500 INTERNAL SERVER ERROR', headers, sys.exc_info())
[Tue May 16 23:08:49.734471 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]   File "/usr/lib/python2.7/site-packages/beaker/middleware.py", line 146, in session_start_response
[Tue May 16 23:08:49.734480 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]     session.persist()
[Tue May 16 23:08:49.734492 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]   File "/usr/lib/python2.7/site-packages/beaker/session.py", line 605, in persist
[Tue May 16 23:08:49.734501 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]     self._session().save()
[Tue May 16 23:08:49.734506 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]   File "/usr/lib/python2.7/site-packages/beaker/session.py", line 275, in save
[Tue May 16 23:08:49.734515 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]     **self.namespace_args)
[Tue May 16 23:08:49.734520 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]   File "/usr/lib/python2.7/site-packages/beaker/container.py", line 524, in __init__
[Tue May 16 23:08:49.734528 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]     util.verify_directory(self.file_dir)
[Tue May 16 23:08:49.734534 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]   File "/usr/lib/python2.7/site-packages/beaker/util.py", line 43, in verify_directory
[Tue May 16 23:08:49.734541 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]     os.makedirs(dir)
[Tue May 16 23:08:49.734547 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]   File "/usr/lib64/python2.7/os.py", line 150, in makedirs
[Tue May 16 23:08:49.734555 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]     makedirs(head, mode)
[Tue May 16 23:08:49.734560 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]   File "/usr/lib64/python2.7/os.py", line 157, in makedirs
[Tue May 16 23:08:49.734567 2017] [:error] [pid 23546] [remote 172.18.157.33:46865]     mkdir(name, mode)
[Tue May 16 23:08:49.734579 2017] [:error] [pid 23546] [remote 172.18.157.33:46865] OSError: [Errno 13] Permission denied: './session'`

and also maybe there is some issue in psql database tables.
![Uploading teset1.png…]()

**Comment by frodrigo** [comment]
If you web server does not run under same user as your installed the source code, you must allow it to write into ./session

**Comment by gzqlovemxq** [comment]
And where does ./session located? Thank you.

**Comment by frodrigo** [comment]
probably in the root of the sources directory

**Comment by jocelynj** [comment]
Were you able to run the frontend ? Do you need more help ?
