### ISSUE TITLE
frontend not working

### ISSUE THREAD

**Issue by johnfreed** [osm-fr/osmose-frontend#60]
The latest change to the frontend has broken it completely for English language using Chrome on Linux.

It is also substantially slower than before and barely usable in French using Chrome on Linux.

It seems more or less okay using Firefox on Linux (though noticeably slower than before).

**Comment by frodrigo** [comment]
There is no language specific computing.
Can you retry? Maybe you test on a heavy load time.
There no noticeable load or delay change from the server side.

**Comment by johnfreed** [comment]
I will retry and also provide more details after I return to Europe in a
few hours. Thanks.

Basic problem is that if I click on my personal list of level 1 2 or 3
items and choose one, it goes to my default map with no pins.

I also noticed in Firefox that for Level 3 items (others untested), no pin
appears, but the map zooms to the correct location. Afterwards if I click
on "all" pins, the (single) pin appears.

Thanks again. More later.

**Comment by johnfreed** [comment]
Similarly if I click on "map these items" when viewing the list of
problems, the default map appears with no pins. Haven't tested to see what
happens if I subsequently select "all" pins from the map view.

**Comment by johnfreed** [comment]
Cleared all ten Openstreetmap cookies and the english-vs-french problem on
Chrome went away.

Other problems still remain on both Chrome and Firefox for Linux.

Problem one:
1) display "user statistics for xxx" for Level 2
2) click on "show issues on a map"
3) default map with no pins is shown. Severity is incorrectly shown as
Level 1
4) changing severity level makes no difference. Selecting all makes no
difference. No pins.

Problem Two:
1) display "user statistics for xxx" for Level 2
2) cllck on any of the problems
3) default map with no pins is shown. Severity is correctly shown as Level 2
4) click on "all"
5) pins appear

Side note on Problem 2. The particular problem was a "Structure" problem,
#1070 "objects overlap". When the map displays, it indicates "1/27" checked
for Structure. However, nothing is checked and only a dozen boxes appear,
not 27. When I click on "all", the pin appears, and it indicates "27/27"
chosen. But the particular category, "objects overlap", still does not
appear (it is among the 15 not shown).

**Comment by frodrigo** [comment]
cd #61
