### ISSUE TITLE
No issue shown when opening URL

### ISSUE THREAD

**Issue by fgouget** [osm-fr/osmose-frontend#61]
To reproduce:
* Start from your personal issues list... or mine:
  https://osmose.openstreetmap.fr/fr/byuser/fgouget?level=1

* Click on the coordinates for the first item. In this case the URL is:
  http://osmose.openstreetmap.fr/en/map/#&item=1270&zoom=17&lat=44.7454833&lon=-0.6183171&level=1

This opens an Osmose window which does not show any pin for that window. The exact result actually depends on your previous Osmose activity:
* You may get no pin at all.
* Or Osmose may show pins for every possible issue.
* Or only the pins for some other issue you looked at before.

Fortunately there is a workaround which is to set 'Severity' to 'all' in the sidebar. Osmose will then refresh the map and show only the expected pins.

This issue started when the new version of Osmose was put online a few days ago.

**Comment by frodrigo** [comment]
The problem already exists before the update.
It needs a rework on how the app deals with URL parameters and cookies.

**Comment by frodrigo** [comment]
Fixed by afa6651c63a6df0258830cd806012b938b4e4388

**Comment by frodrigo** [comment]
The commit afa6651did not fix it :-/

**Comment by frodrigo** [comment]
Fixed :champagne:
