### ISSUE TITLE
"Zoom in" tile with a magnifying glass very confusing

### ISSUE THREAD

**Issue by RicoElectrico** [osm-fr/osmose-frontend#62]
After a while I got what it means, but otherwise it's not the best solution (I know no other map that does this) and in my opinion it's ugly :wink:

**Comment by frodrigo** [comment]
The issues in tile alows many improvement. But we have to limit the number of number of issues in a tile to allow this, and we don't know the real number of issues in a tile. So need a way to show the tile is not complete.
Do have any other idea to display it ? I think cluster look also ugly here.
