### ISSUE TITLE
Corrected errors still on map?

### ISSUE THREAD

**Issue by juhanjuku** [osm-fr/osmose-frontend#63]
Together with introducing "magnifying glass" new UI bug appeared.
Corrected errors remain shown on map. When I click on them, I get message "error"
![screen](https://user-images.githubusercontent.com/12792066/32555396-487900fe-c4a5-11e7-8dec-ff640487209d.png)
They disappear when I zoom in enough, but come out again when zoom out.

**Comment by frodrigo** [comment]
@jocelynj it's caused by cache on vector tiles. Maybe we need to disable it in some way.

**Comment by frodrigo** [comment]
Cache delay fixed to 2min for high zoom.

**Comment by juhanjuku** [comment]
Fixed???
I corrected yesterday many of errors on attached picture, but still see
them today and when I click them, error balloon shows?

**Comment by frodrigo** [comment]
As it's cache on your browser you have to wait for the expiration of the old cache delay (5d) or clear your cache.
