### ISSUE TITLE
RSS-Feed for false positive

### ISSUE THREAD

**Issue by dex2000** [osm-fr/osmose-frontend#64]
I have unchecked a lot of false false positive now, and thought it would be nice to be informed (via RSS) if someone mark an error as false positive.

I have tried on http://osmose.openstreetmap.fr/de/errors/false-positive?country=germany_hessen&item=0 to get the feed, but i got there http://osmose.openstreetmap.fr/de/errors.rss?country=germany_hessen&item=0 ... what is the error-feed.

Is there a way to get the false positive only?

**Comment by frodrigo** [comment]
Works now.

**Comment by dex2000** [comment]
Mhh, is it live? 
Have tried it, and still don't get feed for false positive.

**Comment by frodrigo** [comment]
Humm, for it works, doesn't it ?
http://osmose.openstreetmap.fr/de/errors/false-positive.rss?country=germany_hessen&item=0

What it's the problem for you?

**Comment by dex2000** [comment]
Ah, ok that works, dunno about that link. Where do you get this?
In (for example) http://osmose.openstreetmap.fr/de/errors/false-positive?country=germany_baden_wuerttemberg&item=0 i cannot find this in source code.

**Comment by frodrigo** [comment]
There is no link to it in source code.
