### ISSUE TITLE
Do not display error popup if issue is already solved

### ISSUE THREAD

**Issue by bagage** [osm-fr/osmose-frontend#68]
When you click on popups that were already resolved by some else and/or you in another tab and/or due to a bug in cached tiles, the popup opens with content "error".

It would be great if either:

1) Osmose shows "This issue has already been solved"
2) Osmose still opens the issue but somewhat marks it solved
3) Osmose hides/closes the popup immediately without error

I think 1) would be the best one, but that's up to you.

This is somewhat related to #67 but not exactly the same since here 410 Gone is due to note being already resolved.

**Comment by frodrigo** [comment]
I do not see the point of this issues (vs #67). Since when issues does not more exists in Osmose DB, it's always return a 410 Gone.

**Comment by bagage** [comment]
OK, I wasn't sure if they were related. But if they share the same cause, let's close this one. Thanks @frodrigo .
