### ISSUE TITLE
Search field problem

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-frontend#78]
Field do not stay open (only on mouse hover). Result not clicable.

**Comment by Stefal** [comment]
The field doesn't stay opened with Firefox, but stays opened with Chrome and Edge.
But if you click on a location, the slippy map doesn't move to the destination.

The problem is the same with the "location" button.

**Comment by frodrigo** [comment]
Probably linked to this https://github.com/perliedman/leaflet-control-geocoder/issues/174
But even after update to master I have the same the problem.
We will update Osmose fronted to this as it may add some fix anyway.

**Comment by frodrigo** [comment]
Works with last firefox.

**Comment by Stefal** [comment]
With Edge and Chrome too
