### ISSUE TITLE
No issue shown when opening URL

### ISSUE THREAD

**Issue by bagage** [osm-fr/osmose-frontend#81]
When you try to open some [url](http://osmose.openstreetmap.fr/fr/map/#source=14708&item=7170&class=13&zoom=10&lat=45.0322&lon=5.458&overlays=FFFFFFFFFFFFFFFFFFFFT&level=1%2C2%2C3&tags=&fixable=), Osmose doesn't show anything.
You have to select an item on left menu (and optionally deselect it) to make Osmose show expected markers.
I'd like to work on this but until https://github.com/osm-fr/osmose-backend/issues/263 is fixed (eg. until I have a working dev env), I cannot do much but report issues.

**Comment by frodrigo** [comment]
Duplicate #61.
Help welcome.

**Comment by frodrigo** [comment]
Fixed :champagne:
