### ISSUE TITLE
search is broken

### ISSUE THREAD

**Issue by laurentriffard** [osm-fr/osmose-frontend#86]
hello, 
in osmose frontend, search does not allow to select any of the suggestion.

- click on the magnifier symbol, a text entry field pops up.
- type a few words (e.g. « lyon, france ») and hit « Enter » key. A list of suggestions does appear below the magnifier.
- then, clicking on one of the suggestions does not have any effect.

**Comment by frodrigo** [comment]
Duplicate #78 
Just fixed 10min ago.

**Comment by laurentriffard** [comment]
I confirmed this bug is fixed on chromium/desktop and firefox/mobile. Thanksc

But firefox/desktop is still affected by #78 (i.e. the search results disappears as soon as the mouse is moved)
