### ISSUE TITLE
roundabout : item 9004 vs 4020, ref tag or no ref tag ?

### ISSUE THREAD

**Issue by laurentriffard** [osm-fr/osmose-frontend#87]
Hello, 

these days, I saw new osmose alerts, item 9004 "highway without a reference", on roundabouts with highway=tertiary, or highway=secondary.

If I add a ref= tag to these roundabouts, then Osmose raises a new alert, item 4020 " on junction=roundabout, Should not contain tag ref= "

How can I get it right ? Please, make it coherent.

As a side note, I've got 321 item 9004 anomalies. Secondary or tertiary highways without ref seem to be a well established practice, especially in urban zone. Is it a good idea to raise alerts for such situation ? What should I do ? add noref=yes ? downgrade these ways to unclassified or residential ? mark those alerts as false positive ?

**Comment by laurentriffard** [comment]
oops, should have open it against osmose-backend…

**Comment by frodrigo** [comment]
FYI @Klumbumbus

**Comment by Klumbumbus** [comment]
adapted in JOSM https://josm.openstreetmap.de/changeset/13471/josm

**Comment by Klumbumbus** [comment]
How is the flow from the JOSM code change to osmose?

**Comment by frodrigo** [comment]
@Klumbumbus thank you for dealing with this.
Meanwhile we have droped the support of this level (throwOther) of issues in Osmose.
