### ISSUE TITLE
remove coverage layer

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-frontend#88]
Osmose covers the full planet. 

I see no benefit in showing the coverage layer when everything is covered.

Proposal is to remove the layer to slim down the user interface and to clean up code base.

**Comment by frodrigo** [comment]
The coverage is still not complete:
- Missing "Navassa Island" https://github.com/osm-fr/osmose-backend/issues/87
- Missing oceans

More seriously, I think of reuse it to display data by country.

**Comment by frodrigo** [comment]
Removed.
