### ISSUE TITLE
Permanlinks are not working

### ISSUE THREAD

**Issue by vinber** [osm-fr/osmose-frontend#91]
when i want to share a permalink about an item, first I try in a private windows of firefox.
And it's never what i choosed.

Example with item 3230(amenity=recycling) :
http://osmose.openstreetmap.fr/fr/map/#zoom=13&lat=43.5328&lon=-1.4325&item=3230&level=1%2C2%2C3&tags=&fixable=&overlays=FFFFFFFFFFFFFFFFFFFFT

If you try this link, do you have only item 3230 ?

**Comment by frodrigo** [comment]
Duplicate #61

**Comment by frodrigo** [comment]
Help needed.

**Comment by frodrigo** [comment]
Fixed :champagne:
