### ISSUE TITLE
Error while saving corrections

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-frontend#94]
cf screen-shot
![screenshot_20180517_101316](https://user-images.githubusercontent.com/36087963/40165054-5d49f226-59bb-11e8-8f12-89390924573a.png)

Firefox ESR 52.7.3 Debian 9

**Comment by Bibi56** [comment]
+1 :-(

**Comment by frodrigo** [comment]
Probably not the same error.

Fixed, yesterday, and deployed Now. Issue with utf-8 char in tags values.

Please, retest.

**Comment by Bibi56** [comment]
Yes many possibilities for 500 error. It works! You can close the ticket except if @deuzeffe doesn't want to. Ce que femme veut !
